### ISSUE TITLE
Saving the trained models in pb format

### ISSUE THREAD

**Issue by mrkaworu** [tensorlayer/hyperpose#131]
Hello,

First of all thank you for your hard work. I've able to train and save some networks in the npz format but I would like to export the models to .pb to be more easily deployable. I've been working in freezing the graph and saving it to a pb file through tf.graph_util.convert_variables_to_constants and tf.graph_util.remove_training_nodes but I'm unsure of what are the names of the output nodes for the vggtiny model?

By the way, do you plan to provide an easy way to save the models in pb using tensorlayer?

**Comment by PrinceP** [comment]
```
def model_func():
    image, conf, paf = get_model(base_model_name)(target_size, 'channels_first')
    return [image], [conf, paf]

```
get_model function can be imported from 
`from openpose_plus.models import _input_image, get_model`

From examples/uff-runner.py file.

**Comment by luomai** [comment]
Thanks @PrinceP for answering this question! 👍

**Comment by drt040312** [comment]
I lifted the train.py
"
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
"
Comment
Training in single simgle mode
run
Python3 train.py
Then use nvidia-smi to view the gpu usage, and did not see the training related gpu usage information

**Comment by drt040312** [comment]
@luomai

**Comment by BadMachine** [comment]
@PrinceP 
Could you provide more info about converting npz to pb, pbtxt?

**Comment by PrinceP** [comment]
Sorry for the late reply. 

You can follow the https://github.com/tensorlayer/openpose-plus/blob/master/examples/uff-runner.py#L120
and subsequent lines of code for using the npz models. 

    measure(lambda: tl.files.load_and_assign_npz_dict(args.path_to_npz, sess), 'load npz')
    frozen_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph_def, output_names)
    tf_model = tf.graph_util.remove_training_nodes(frozen_graph)
    uff_model = measure(lambda: uff.from_tensorflow(tf_model, output_names), 'uff.from_tensorflow')
