### ISSUE TITLE
Training very CPU intensive

### ISSUE THREAD

**Issue by jpapon** [tensorlayer/hyperpose#150]
First off, awesome library, some great work here!

Just a question/comment : I'm currently running training the hao28_experimental model, and I've found training is *very* CPU intensive. To the point that my GPUs are sitting idle much of the time, and all of my CPU cores are under heavy load constantly.
Is this due to data augmentation? Would you recommend disabling some augmentation steps to remove this CPU bottleneck?

**Comment by luomai** [comment]
Hey @jpapon , thanks for using our project.

As you can see from the [data augmentation function](https://github.com/tensorlayer/openpose-plus/blob/master/train.py#L120), there are quite a few steps to augment the images. However, some of them might be redundant if your deployment environment is more controllable. For example, we add a step to randomly adjust the brightness of the images. In your application, if the brightness is constant, you may consider excluding this step.  

In general, the data augmentation is very application-specific. You can customise for your own need. This, however, would require iteratively tuning of the augmentation.  All steps in the current implementation are added for specific purposes.

@zsdonghao Thought?

**Comment by drt040312** [comment]
Hello, I am using the engineering training vgg model, but the GPU is not being used. Where do I need to perform the setup?

**Comment by feifeiysd** [comment]
@drt040312  I met the same issue, GPU is always 0%. do you resolve it?

**Comment by gachiemchiep** [comment]
@drt040312 
@feifeiysd 

There're 2 lines inside train.py that need to comment out.

```bash
# un-comment 2 lines below to use gpu
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3"
```

After changing, the output log should have the following lines

```bash
2019-04-10 09:14:47.717336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30378 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:18:00.0, compute capability: 7.0)
2019-04-10 09:14:47.718983: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30378 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2019-04-10 09:14:47.720378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30378 MB memory) -> physical GPU (device: 2, name: Tesla V100-PCIE-32GB, pci bus id: 0000:86:00.0, compute capability: 7.0)
2019-04-10 09:14:47.721387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30378 MB memory) -> physical GPU (device: 3, name: Tesla V100-PCIE-32GB, pci bus id: 0000:af:00.0, compute capability: 7.0)
[TL] ERROR: file models/pose.npz doesn't exist.
Total Loss at iteration 1 / 600000 is: 1688.8099365234375 Learning rate 4.000000e-05 l2_loss 1.698877e+00 Took: 14.11396598815918s
Network# 0 For Branch 1 Loss: 1041.7161
Network# 1 For Branch 2 Loss: 83.49345
Network# 2 For Branch 1 Loss: 1040.8175
Network# 3 For Branch 2 Loss: 83.43689
Network# 4 For Branch 1 Loss: 1041.2842
Network# 5 For Branch 2 Loss: 83.474075
Total Loss at iteration 2 / 600000 is: 1534.257568359375 Learning rate 4.000000e-05 l2_loss 1.698877e+00 Took: 1.779259443283081s
Network# 0 For Branch 1 Loss: 908.3803
Network# 1 For Branch 2 Loss: 104.04921
Network# 2 For Branch 1 Loss: 911.49396
Network# 3 For Branch 2 Loss: 103.97606
Network# 4 For Branch 1 Loss: 933.1764
Network# 5 For Branch 2 Loss: 104.04149
Total Loss at iteration 3 / 600000 is: 1207.9090576171875 Learning rate 4.000000e-05 l2_loss 1.698881e+00 Took: 5.82180380821228s

```

**Comment by ins7itia** [comment]
@gachiemchiep Did you check GPU utilization by `nvidia-smi`?

I also faced similar issue, which causes CPU intensive training session. While CPU cores running busy all the time, GPU is being idle - then at the end of step, GPU seems to be running.

My desktop setup with 980Ti gives similar result whether uncomment above codes or not. (~2s / step)

**Comment by YinXiaojieCSDN** [comment]
> @gachiemchiep Did you check GPU utilization by `nvidia-smi`?
> 
> I also faced similar issue, which causes CPU intensive training session. While CPU cores running busy all the time, GPU is being idle - then at the end of step, GPU seems to be running.
> 
> My desktop setup with 980Ti gives similar result whether uncomment above codes or not. (~2s / step)

Hello,
        I meet the same promblem,I want to ask you have you sloved it?

**Comment by gachiemchiep** [comment]
@ins7itia @YinXiaojieCSDN 

My training log is as follow: 

[train.log](https://github.com/tensorlayer/openpose-plus/files/3567216/train.log)

I use the batch = 1 so the time took for one batch is as follow 

```bash
Total Loss at iteration 5 / 600000 is: 8783.7177734375 Learning rate 4.000000e-05 l2_loss 8.544054e+03 Took: 0.4861624240875244s
```

The nvidia-smi output is as follow. As you can see, it took up to 4.8Gb GPU memory to train (batch_size=1)

```bash
Tue Sep  3 08:13:21 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:1F:00.0  On |                  N/A |
| 44%   60C    P2    69W / 120W |   5906MiB /  6075MiB |     94%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       695      C   python                                      4295MiB |
|    0      1710      G   /usr/lib/xorg/Xorg                           547MiB |
|    0      3494      G   ...quest-channel-token=3052683709036606959   950MiB |
|    0     13786      G   ...uest-channel-token=14646620780440049126    43MiB |


```

I paste the diff files here. Hope this will help

```bash
diff --git a/train.py b/train.py
index b2d3a84..70fee0e 100755
--- a/train.py
+++ b/train.py
@@ -29,8 +29,8 @@ tl.logging.set_verbosity(tl.logging.DEBUG)
 tl.files.exists_or_mkdir(config.LOG.vis_path, verbose=False)  # to save visualization results
 tl.files.exists_or_mkdir(config.MODEL.model_path, verbose=False)  # to save model files
 
-# os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
-# os.environ["CUDA_VISIBLE_DEVICES"] = "0"
+os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
+os.environ["CUDA_VISIBLE_DEVICES"] = "0"
 
 # FIXME: Don't use global variables.
 # define hyper-parameters for training


diff --git a/train_config.py b/train_config.py
index a55c3c2..e33d184 100644
--- a/train_config.py
+++ b/train_config.py
@@ -5,7 +5,7 @@ from easydict import EasyDict as edict
 config = edict()
 
 config.TRAIN = edict()
-config.TRAIN.batch_size = 8
+config.TRAIN.batch_size = 1
 config.TRAIN.save_interval = 5000
 config.TRAIN.log_interval = 1
 # config.TRAIN.n_epoch = 80
@@ -23,14 +23,14 @@ config.MODEL.hin = 368  # input size during training , 240
 config.MODEL.win = 368
 config.MODEL.hout = int(config.MODEL.hin / 8)  # output size during training (default 46)
 config.MODEL.wout = int(config.MODEL.win / 8)
-config.MODEL.name = 'vgg'  # vgg, vggtiny, mobilenet
+config.MODEL.name = 'mobilenet'  # vgg, vggtiny, mobilenet
 
 if (config.MODEL.hin % 16 != 0) or (config.MODEL.win % 16 != 0):
     raise Exception("image size should be divided by 16")
 
 config.DATA = edict()
 config.DATA.train_data = 'coco'  # coco, custom, coco_and_custom
-config.DATA.coco_version = '2017'  # MSCOCO version 2014 or 2017
+config.DATA.coco_version = '2014'  # MSCOCO version 2014 or 2017
 config.DATA.data_path = 'data'
 config.DATA.your_images_path = os.path.join('data', 'your_data', 'images')

```

**Comment by ins7itia** [comment]
@YinXiaojieCSDN @gachiemchiep 
I see. I think I should explain more about my case. When I'm training with Keras or TF, usually GPU utilization is almost always at high(Volatile GPU-Util value in `nvidia-smi`), which is not in openpose-plus training.

You can observe this behavior when you use a command such as `nvidia-smi -lms 500`, where GPU utilization is almost at 0 then occasionally hit 100%. 

I guess it is related to the pre-process @luomai mentioned  https://github.com/tensorlayer/openpose-plus/issues/150#issuecomment-439044668, not sure though. If that's the case, setting smaller batch size may reduce GPU idle time.

**Comment by gachiemchiep** [comment]
@ins7itia @YinXiaojieCSDN 
Can you post your train log and nvidia-smi log?
as i my case, the following process is openpose-plus training process and it is online on the time

```bash
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       695      C   python                                      4295MiB |
```

There're some line inside **def _data_aug_fn(image, ground_truth):** method which used cpu-only. 
So there's large chance that you're having bottle neck at the dataset loading stage. 
![image](https://www.tensorflow.org/images/datasets_without_pipelining.png)

Maybe you should try to increase the number of cpu used for dataset loading and the prefetch/cache.
![image](https://www.tensorflow.org/images/datasets_with_pipelining.png)

```python
def single_train(training_dataset):
    ds = training_dataset.shuffle(buffer_size=4096)  # shuffle before loading images
    ds = ds.repeat(n_epoch)
    // Increase numper of cpu use for dataset loading
    ds = ds.map(_map_fn, num_parallel_calls=multiprocessing.cpu_count() // 2)  # decouple the heavy map_fn
    ds = ds.batch(batch_size)  # TODO: consider using tf.contrib.map_and_batch
    // Increase prefet/cache
    ds = ds.prefetch(2)
```

**Comment by ins7itia** [comment]
@YinXiaojieCSDN @gachiemchiep
Here is sample log of my case (crop of `nvidia-smi` at 100 ms timeframe):

```

| N/A   47C    P0    61W / 300W |  24204MiB / 32499MiB |      6%      Default |
| N/A   46C    P0    61W / 300W |  24204MiB / 32499MiB |      3%      Default |
... (ommited)
| N/A   46C    P0    61W / 300W |  24204MiB / 32499MiB |      5%      Default |
| N/A   48C    P0   160W / 300W |  24204MiB / 32499MiB |     13%      Default |
| N/A   47C    P0    63W / 300W |  24204MiB / 32499MiB |     31%      Default |
| N/A   47C    P0    68W / 300W |  24204MiB / 32499MiB |      2%      Default |
... (ommited)
```

and here's a sample of train log:
```
Total Loss at iteration 253 / 600000 is: 178.69873046875 Learning rate 4.000000e-05 l2_loss 2.354225e+00 Took: 5.554751396179199s
Total Loss at iteration 254 / 600000 is: 144.69320678710938 Learning rate 4.000000e-05 l2_loss 2.354222e+00 Took: 4.560063600540161s
Total Loss at iteration 255 / 600000 is: 154.9602813720703 Learning rate 4.000000e-05 l2_loss 2.354217e+00 Took: 2.7776236534118652s
Total Loss at iteration 256 / 600000 is: 131.13514709472656 Learning rate 4.000000e-05 l2_loss 2.354214e+00 Took: 2.2247231006622314s

```

I think you're right about **_data_aug_fn**; There seems to be some overheads at data loading. So I'll need to reduce augmentation or increase prefetch size.

Thank you for your help!

**Comment by gachiemchiep** [comment]
@ins7itia 
Good to know.
By the way, if my comment really help you then could you mind paste your speed improvement result here ?  it would help other people someday.

**Comment by YinXiaojieCSDN** [comment]
> @ins7itia
> Good to know.
> By the way, if my comment really help you then could you mind paste your speed improvement result here ? it would help other people someday.

I do no think your method is ok. Because you decrease the batchsize ,the  number of pictures trained will be relatively reduced. Meanwhile if the batchsize is very low,the effect of convergence will also decrease.

**Comment by YinXiaojieCSDN** [comment]
Have you sloved it?How to modify it in the code

**Comment by YinXiaojieCSDN** [comment]
> > @ins7itia
> > Good to know.
> > By the way, if my comment really help you then could you mind paste your speed improvement result here ? it would help other people someday.
> 
> I do no think your method is ok. Because you decrease the batchsize ,the number of pictures trained will be relatively reduced. Meanwhile if the batchsize is very low,the effect of convergence will also decrease.

You have trained 8 photos in the previous iteration and now train 1 piece. So the time used is still the same.

**Comment by YinXiaojieCSDN** [comment]
> Hey @jpapon , thanks for using our project.
> 
> As you can see from the [data augmentation function](https://github.com/tensorlayer/openpose-plus/blob/master/train.py#L120), there are quite a few steps to augment the images. However, some of them might be redundant if your deployment environment is more controllable. For example, we add a step to randomly adjust the brightness of the images. In your application, if the brightness is constant, you may consider excluding this step.
> 
> In general, the data augmentation is very application-specific. You can customise for your own need. This, however, would require iteratively tuning of the augmentation. All steps in the current implementation are added for specific purposes.
> 
> @zsdonghao Thought?

您好，我想知道您在训练的时候是不是也有这种几乎不用gpu的情况出现，我们应该在代码中怎么解决它呢。

**Comment by ins7itia** [comment]
> > @ins7itia
> > Good to know.
> > By the way, if my comment really help you then could you mind paste your speed improvement result here ? it would help other people someday.
> 
> I do no think your method is ok. Because you decrease the batchsize ,the number of pictures trained will be relatively reduced. Meanwhile if the batchsize is very low,the effect of convergence will also decrease.

I agree with you. But performance-wise, I think adjusting prefetch size / cpu counts may help to improve. I didn't test it yet however, since I'm pretty much occupied currently. I hope soon I could update the result. Thank you!

**Comment by gachiemchiep** [comment]
@YinXiaojieCSDN 
> > @ins7itia
> > Good to know.
> > By the way, if my comment really help you then could you mind paste your speed improvement result here ? it would help other people someday.
> 
> I do no think your method is ok. Because you decrease the batchsize ,the number of pictures trained will be relatively reduced. Meanwhile if the batchsize is very low,the effect of convergence will also decrease.

No no, the correct one should be both : 
1. enable gpu for training: https://github.com/tensorlayer/openpose-plus/issues/150#issuecomment-481486374
1. : **increase the prefetch and cpu core** used for fetching data :  https://github.com/tensorlayer/openpose-plus/issues/150#issuecomment-527684094 . 

The batch size = 1 used in the log only for demostratte that GPU can be used for training. The v100 is not always available for me so i reduce the batch.

**Comment by ins7itia** [comment]
> @YinXiaojieCSDN
> 
> > > @ins7itia
> > > Good to know.
> > > By the way, if my comment really help you then could you mind paste your speed improvement result here ? it would help other people someday.
> > 
> > 
> > I do no think your method is ok. Because you decrease the batchsize ,the number of pictures trained will be relatively reduced. Meanwhile if the batchsize is very low,the effect of convergence will also decrease.
> 
> No no, the correct one should be both :
> 
> 1. enable gpu for training: [#150 (comment)](https://github.com/tensorlayer/openpose-plus/issues/150#issuecomment-481486374)
> 2. : **increase the prefetch and cpu core** used for fetching data :  [#150 (comment)](https://github.com/tensorlayer/openpose-plus/issues/150#issuecomment-527684094) .
> 
> The batch size = 1 used in the log only for demostratte that GPU can be used for training. The v100 is not always available for me so i reduce the batch.

I tried prefetch / cpu core counts on GeForce RTX 2080 Ti and shown no improvement.
Here's my oconfiguration:
- My `multiprocessing.cpu_count()` returns 12, which means in original code `num_parallel_calls` is set to 6.
- Prefetch size is set to 2 by default.
- I used 'vggtiny' model.


Here's cropped log with original training **(avg. step time : 2.42s)**:
```
Total Loss at iteration 57 / 600000 is: 268.08984375 Learning rate 4.000000e-05 l2_loss 1.699434e+00 Took: 2.1398589611053467s
Total Loss at iteration 58 / 600000 is: 472.4797058105469 Learning rate 4.000000e-05 l2_loss 1.699432e+00 Took: 3.769688367843628s
Total Loss at iteration 59 / 600000 is: 373.49005126953125 Learning rate 4.000000e-05 l2_loss 1.699431e+00 Took: 2.674827814102173s
Total Loss at iteration 60 / 600000 is: 224.01690673828125 Learning rate 4.000000e-05 l2_loss 1.699430e+00 Took: 1.2234010696411133s
Total Loss at iteration 61 / 600000 is: 195.55703735351562 Learning rate 4.000000e-05 l2_loss 1.699429e+00 Took: 2.293491840362549s
```

Now when I changed prefetch size from 2 to 12 **(avg. step time : 2.22s)**:
```
Total Loss at iteration 40 / 600000 is: 375.73883056640625 Learning rate 4.000000e-05 l2_loss 1.699222e+00 Took: 3.8462207317352295s
Total Loss at iteration 41 / 600000 is: 251.95755004882812 Learning rate 4.000000e-05 l2_loss 1.699220e+00 Took: 1.1204919815063477s
Total Loss at iteration 42 / 600000 is: 420.48187255859375 Learning rate 4.000000e-05 l2_loss 1.699217e+00 Took: 3.403477668762207s
Total Loss at iteration 43 / 600000 is: 214.3637237548828 Learning rate 4.000000e-05 l2_loss 1.699215e+00 Took: 1.657869815826416s
Total Loss at iteration 44 / 600000 is: 142.03358459472656 Learning rate 4.000000e-05 l2_loss 1.699213e+00 Took: 1.0477614402770996s
```

When I changed `num_parallel_calls` from 6 to 12 **(avg. step time : 2.96s)**:
```
Total Loss at iteration 32 / 600000 is: 296.7987365722656 Learning rate 4.000000e-05 l2_loss 1.697858e+00 Took: 1.555290937423706s
Total Loss at iteration 33 / 600000 is: 286.3978576660156 Learning rate 4.000000e-05 l2_loss 1.697853e+00 Took: 5.4844114780426025s
Total Loss at iteration 34 / 600000 is: 268.2082214355469 Learning rate 4.000000e-05 l2_loss 1.697849e+00 Took: 0.5681366920471191s
Total Loss at iteration 35 / 600000 is: 245.64508056640625 Learning rate 4.000000e-05 l2_loss 1.697845e+00 Took: 1.967331886291504s
Total Loss at iteration 36 / 600000 is: 284.550048828125 Learning rate 4.000000e-05 l2_loss 1.697841e+00 Took: 5.24184775352478s
```

Unfortunately, I don't see a relevant performance changes. In fact, increasing `num_parallel_calls` seems to inducing stalls.

I couldn't afford to get more detailed result, but hope that above numbers help others who considers to modifying those parameters.
