### ISSUE TITLE
tx2 testing

### ISSUE THREAD

**Issue by drt040312** [tensorlayer/hyperpose#156]
Hi  sir !
     I have successfully compiled the project on TX2, the image tested is 384x256,
There are two people in the picture, the running script is: run-uff-cpp.sh, I have closed the drawing result and the save function, but the display speed is only 4fps.
Did not reach the 13FPS in the project introduction, is there any problem with my operation? The results of the operation and the pictures I put in the attachment are:
The function that closes the image is shown below, I changed true to false
""
bool draw_humans = true;
                if (draw_humans) {
                    cv::Mat resized_image(cv::Size(width, height), CV_8UC(3),
                                          p.hwc_ptr);
                    handle(resized_image, humans);
                }

""

**Comment by drt040312** [comment]
![result](https://user-images.githubusercontent.com/32739006/48683516-99cba400-ebe8-11e8-8fb1-d3d14fe88e09.png)

**Comment by drt040312** [comment]
![_20181119105007](https://user-images.githubusercontent.com/32739006/48683592-efa04c00-ebe8-11e8-9172-5b300bfb6381.jpg)

**Comment by drt040312** [comment]
>           Which tensorrt version are you using ?

I use jecpack3.3 to refresh my TX2, the display is tensorrt 4.0

**Comment by drt040312** [comment]
I found an interesting phenomenon. When I changed the value of repeat in run-uff-cpp to 2, the result output was 4fps. When I changed the value of repeat to 20, it output 11fps.
There may be a fixed time T in the run() function, then the method of testing time given by the project should be problematic.

**Comment by drt040312** [comment]
I don't understand what it means to save predictions. The running logic of this project should be to run a picture 20 times and then calculate the average time.

**Comment by lgarithm** [comment]
@drt040312 yes, there is a fixed time T in the run() function, it will do some one-time initialisation, like allocating memory buffer. 
Therefore when we measuring the mean, we run 20 or more times to average down the initialisation cost.

**Comment by drt040312** [comment]
Can you separate the initialization operation in the run() function from the project? If the project is integrated into another project, the overall time is less than 13fps;
If not, the project may not be available for real-time projects

**Comment by lgarithm** [comment]
Which API would you like to integrate into other project?

Currently the initialization is done in 

`create_pose_detection_runner` and `create_paf_processor` 

the inference is done in

`paf_processor::operator()` and `pose_detection_runner::operator()`.

Users are supposed to call 

`create_pose_detection_runner` and `create_paf_processor` 

once and then call the `operator()` method on the returned objects.

**Comment by drt040312** [comment]
I want to make changes based on the example_stream_dector.bin project, because it is harder for me to call the api to write the project again.
Can you give me some guidance?thank you

**Comment by lgarithm** [comment]
The files in the `examples` folder are not part of the API, you can just copy them into your own project and make any modification as you like.

**Comment by drt040312** [comment]
Hi sir  !
After our general summary, we think it is more appropriate to call the API solution.
Can you give me a c++ source project to explain how to use the API?
thanks very much!

**Comment by drt040312** [comment]
Hi sir !
In the example_stream_bin project, the class stream_detector_impl seems to have called the api
So I still want to ask if I can put some initialization functions in run() at the beginning of our project and only execute them once.
Then loop through the image analysis so that we can independently test the operation time of a single image.
This is my idea of integrating the example_stream_bin project into other projects.
The problem I am having now is that I can't see from the code which parts of the run() function belong to the initialization function;
can you give me some help?thanks

**Comment by lgarithm** [comment]
I just took a look at `example_stream_detector.cpp `, currently the profiling is **NOT** counting the initialization (which happens in `stream_detector::create`).
I think the pipeline needs more cycles to warmup.

**Comment by feifeiysd** [comment]
> Can you separate the initialization operation in the run() function from the project? If the project is integrated into another project, the overall time is less than 13fps;
> If not, the project may not be available for real-time projects

Hi , would you like to share your trained model, because it takes too long time to train. thanks!!

**Comment by feifeiysd** [comment]
@drt040312  Hi , would you like to share your model to me? because it takes too much time to train it. thanks !!
