### ISSUE TITLE
3D pose estimation training method

### ISSUE THREAD

**Issue by drt040312** [tensorlayer/hyperpose#159]
HI SIR!
We are currently working on a human body test (similar to the picture below) with a head-top view.

However, we found that openpose is not good for this form of human detection, and there are a lot of missed detections and misdetections.
Sometimes the foot is detected as a hand, sometimes the handle is detected as a foot, which I think is because of the data set used in its model training and the model definition itself.

We know that the key points of the openpose body key point during training are as follows:
{0-'nose', 1-'neck', 2-'Rsho', 3-'Relb', 4-'Rwri',5-'Lsho', 6-'Lelb', 7-'Lwri', 8-'Rhip', 9-'Rkne', 10-'Rank', 11-'Lhip', 12-'Lkne', 13-'Lank', 14-'Leye', 15-'Reye', 16-'Lear', 17-'Rear', 18-'pt19'}
My idea for the overhead view is whether I can focus only on the upper body, that is, keep the label
{, 2-'Rsho', 3-'Relb', 4-'Rwri',5-'Lsho', 6-'Lelb', 7-'Lwri', 18-'pt19'}
And add a "head";
Is this feasible? If so, does the training code need to be modified? and How ?

**Comment by drt040312** [comment]
![qq 20181121154047](https://user-images.githubusercontent.com/32739006/48878445-61270700-ee42-11e8-9cdf-14e884073644.png)

**Comment by zsdonghao** [comment]
@drt040312 Hi, what you need is 3D pose estimation.

**Comment by drt040312** [comment]
Hello, the result model I trained with the training project is pose.npz, and the run-uff-cpp.sh file uses the ".uff" file. How can I use pose.npz to test the effect on the run_stream_example project?

**Comment by akhalili** [comment]
Hi @drt040312  do you have any result on your training?
Also do you have the dataset to share?

Thanks

**Comment by mamoonik** [comment]
Hi has any progress been made on this problem? We are trying to estimate the human head and top view of the pose skeleton from top view to calculate head rotation angle of head to the right and left  direction in a physiotherapy setting
