### ISSUE TITLE
Keypoint location is very weired

### ISSUE THREAD

**Issue by mengzhangjian** [tensorlayer/hyperpose#161]
in vis.cpp's draw_function, I print the part_idx and its point,for COCO_val2014_000000000459.jpg ,I found the predicted point 0, 2, 3, 5 ,6 ,7 is correct. while 14,15,16,17 is not right corresponding to the coco API.

**Comment by lurenjiajingsi** [comment]
问下你是用openpose-puls还是自己用TensorRT实现的？我用openpose-puls，但是运行example_live_camera.cpp，不能检测到人，我使用的模型为hao28-600000-256x384.uff，测试图像为256x384
