### ISSUE TITLE
Tensorrt5 support

### ISSUE THREAD

**Issue by Tamme** [tensorlayer/hyperpose#182]
Hi.

You pose detector worked very well with tensorRT 4, but now after upgrade to cuda10+tensorrt5, it never finds a human. Does anyone have any info on this?

Will investigate more tomorrow.

**Comment by jinfagang** [comment]
@Tamme Same error here, do you have any suggestions?

**Comment by Tamme** [comment]
Didnt have time for it yet, but you could try either retraining/finetuning using tensorrt5 or find where the calculation difference comes from.

**Comment by hesmar** [comment]
Same issue here.
@Tamme or @jinfagang: Did you found a solution?

**Comment by akhalili** [comment]
same here @Tamme  @jinfagang  @hesmar

**Comment by atyshka** [comment]
+1 on this. I'm not sure what could be wrong, tensorrt 5 didn't seem to have any major breaking changes. Please keep us posted if anyone finds a solution. Do the python bindings also fail? @lgarithm Do you plan to look into this?

**Comment by Tamme** [comment]
I did retraining for 5 days, but for some reason that didnt improve the results either...

**Comment by bultmann-s** [comment]
Hi,
I faced the same problem trying to run the live camera example on JetsonNano (cuda10, TensorRT 5).
It seems that the order of the output-buffers registered in tensorRT changed.

The output from uff_runner_impl::createBuffers_ in my case is:
binding 0: name: image type: 0 (3, 256, 384)
binding 1: name: outputs/paf type: 0 (38, 32, 48)
binding 2: name: outputs/conf type: 0 (19, 32, 48)

I got the demo to work by changing the order in line 113, stream_detector.cpp from
{q.heatmap_ptr, q.paf_ptr} to {q.paf_ptr, q.heatmap_ptr}.

**Comment by akhalili** [comment]
@bultmann-s Thanks , it worked for me as well. We should mark this issue as solved
