### ISSUE TITLE
Uff export

### ISSUE THREAD

**Issue by bela127** [tensorlayer/hyperpose#188]
same issue as in #157 
#157 has no fix, don't know why its closed

**Comment by Yulstek** [comment]
Have you changed the model name in export-uff.sh?

**Comment by bela127** [comment]
Yes I did.

Is mobilnet supported (it's marked as experimentelle in one comment)

I will upload the code and errors in the next couple of weeks...
Maybe it helps

**Comment by Yulstek** [comment]
I solved this problem when I changed this line export_uff  **vggtiny** pose2000.npz hao28-${height}x${width}.uff.

**Comment by Yulstek** [comment]
I solved this problem when I changed this line export_uff  vggtiny pose2000.npz hao28-${height}x${width}.uff.
