### ISSUE TITLE
Problems with live-camera.sh

### ISSUE THREAD

**Issue by patrickESM** [tensorlayer/hyperpose#189]
Hello,

i'm currently trying to run the openpose-plus live-camera application.

there are different types of behavior i get when running the program. By that i mean diefferent errors:

For example:

```
binding 0: name: image type0(3, 256, 384)
binding 1: name: outputs/conf type0(19, 32, 48)
binding 2: name: outputs/paf type0(38, 32, 48)
#0 :: 480 x 640
#1 :: 480 x 640
selected 0 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 0-th image
#2 :: 480 x 640
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
example-live-camera: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

```

or the application runs, but no camera image opens and the application just gets stuck
```
binding 0: name: image type0(3, 256, 384)
binding 1: name: outputs/conf type0(19, 32, 48)
binding 2: name: outputs/paf type0(38, 32, 48)
#0 :: 480 x 640
#1 :: 480 x 640
selected 0 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 0-th image
#2 :: 480 x 640
#3 :: 480 x 640
#4 :: 480 x 640
#5 :: 480 x 640
#6 :: 480 x 640
#7 :: 480 x 640
#8 :: 480 x 640
#9 :: 480 x 640
#10 :: 480 x 640
#11 :: 480 x 640
#12 :: 480 x 640
#13 :: 480 x 640
#14 :: 480 x 640
#15 :: 480 x 640
#16 :: 480 x 640
#17 :: 480 x 640
#18 :: 480 x 640
#19 :: 480 x 640
#20 :: 480 x 640
#21 :: 480 x 640
#22 :: 480 x 640
#23 :: 480 x 640
#24 :: 480 x 640
#25 :: 480 x 640
#26 :: 480 x 640
#27 :: 480 x 640
#28 :: 480 x 640
```

and one time it actually worked!

./configure output:

```
usinig CMAKE_EXPORT_COMPILE_COMMANDS=ON
usinig CMAKE_BUILD_TYPE=Release
usinig EXECUTABLE_OUTPUT_PATH=/home/pschuelein/projects/openpose-plus/bin
usinig LIBRARY_OUTPUT_PATH=/home/pschuelein/projects/openpose-plus/lib
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenCV: /usr/local (found version "3.4.5") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
CMake Warning at cmake/examples.cmake:2 (FIND_PACKAGE):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:22 (INCLUDE)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pschuelein/projects/openpose-plus
```

concerning gflags:
i got it installed via `sudo apt install libgflags-dev`

installed libs:
nvidia driver version 384.130 
Cuda 9.0 per runfile
all Cuda9.0 patches
cudnn 7.5 for cuda 9.0 with .tar file
TensorRt 4.0.1 with tar file
opencv 3.4 self build , also make install executed
pip install -r requirements.txt on seperate conda environment openpose-plus

I'm looking forward to your replies.
Thank you all in advance

Patrick

**Comment by patrickESM** [comment]
A colleague of mine figured out it has something to do with opencv.
When we comment out the  imshow line in display the program runs just fine! without any crashes but of course without a displayed camera image.

```
struct screen_t {
    const std::string name;
    const int fps;
    const int delay;

    screen_t(const std::string &name, int fps = 24)
        : name(name), fps(fps), delay(1000 / fps)
    {
    }

    void display(const cv::Mat &frame)
    {
//        cv::imshow(name, frame);
//        cv::waitKey(delay);
    }
};
```

also i forgot to mention that the used opencv version is 3.4.5

**Comment by akhalili** [comment]
I am able to run the live stream. But it doesn't detect any person:

Jetson Nano , TensorRT 5, Opencv 4.1.0.

Any adivce?

**Comment by mnshh17** [comment]
Hello Guys,
I am unable to run live-camera.sh for jetpack 4.2.1

Specifications:
Cuda 10
TRT 5.1
CUDNN 7.5
Opencv 3.4.0

> binding 0: name: image type0(3, 256, 384)
binding 1: name: outputs/paf type0(38, 32, 48)
binding 2: name: outputs/conf type0(19, 32, 48)
Invalid MIT-MAGIC-COOKIE-1 keynvbuf_utils: Could not get EGL display connection
Invalid MIT-MAGIC-COOKIE-1 keynvbuf_utils: Could not get EGL display connection
Opening in O_NONBLOCKING MODE 
#0 :: 480 x 640
#1 :: 480 x 640
#2 :: 480 x 640
selected 8 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 0-th image
Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
(result:31379): Gtk-WARNING **: 18:14:45.991: cannot open display: :0
#3 :: 480 x 640
OpenCV Error: Assertion failed (key_ != -1 && "Can't fetch data from terminated TLS container.") in getData, file /home/nvidia/OpenCV/opencv-3.4.0/modules/core/src/system.cpp, line 1532
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/nvidia/OpenCV/opencv-3.4.0/modules/core/src/system.cpp:1532: error: (-215) key_ != -1 && "Can't fetch data from terminated TLS container." in function getData
Aborted (core dumped)

**Comment by yohoochen** [comment]
> Hello Guys,
> I am unable to run live-camera.sh for jetpack 4.2.1
> 
> Specifications:
> Cuda 10
> TRT 5.1
> CUDNN 7.5
> Opencv 3.4.0
> 
> > binding 0: name: image type0(3, 256, 384)
> > binding 1: name: outputs/paf type0(38, 32, 48)
> > binding 2: name: outputs/conf type0(19, 32, 48)
> > Invalid MIT-MAGIC-COOKIE-1 keynvbuf_utils: Could not get EGL display connection
> > Invalid MIT-MAGIC-COOKIE-1 keynvbuf_utils: Could not get EGL display connection
> > Opening in O_NONBLOCKING MODE
> > #0 :: 480 x 640
> > #1 :: 480 x 640
> > #2 :: 480 x 640
> > selected 8 peaks with value > 0.050000
> > got 0 incomplete humans
> > got 0 humans
> > got 0 humnas from 0-th image
> > Invalid MIT-MAGIC-COOKIE-1 keyUnable to init server: Could not connect: Connection refused
> > (result:31379): Gtk-WARNING **: 18:14:45.991: cannot open display: :0
> > #3 :: 480 x 640
> > OpenCV Error: Assertion failed (key_ != -1 && "Can't fetch data from terminated TLS container.") in getData, file /home/nvidia/OpenCV/opencv-3.4.0/modules/core/src/system.cpp, line 1532
> > terminate called after throwing an instance of 'cv::Exception'
> > what():  /home/nvidia/OpenCV/opencv-3.4.0/modules/core/src/system.cpp:1532: error: (-215) key_ != -1 && "Can't fetch data from terminated TLS container." in function getData
> > Aborted (core dumped)

I have meet the very same problem!!  DId you solve this problem, sir?

**Comment by lurenjiajingsi** [comment]
I also encountered the same problem. 
I can run live-camera. Sh, but I can't detect people
The model I used is: hao28-600000-256x384.uff
Cuda 9.0
Opencv 3.4.2
TensorRT 6
Nvidia p102-100
The input image is 640 by 480

**Comment by Raven888888** [comment]
> 
> 
> I am able to run the live stream. But it doesn't detect any person:
> 
> Jetson Nano , TensorRT 5, Opencv 4.1.0.
> 
> Any adivce?



> 
> 
> I also encountered the same problem.
> I can run live-camera. Sh, but I can't detect people
> The model I used is: hao28-600000-256x384.uff
> Cuda 9.0
> Opencv 3.4.2
> TensorRT 6
> Nvidia p102-100
> The input image is 640 by 480

Same here. I am also using model https://www.makeartwithpython.com/blog/deep-learning-from-scratch-on-the-jetson-nano/
It is run on my webcam. Never detect anything despite everything is working.
