### ISSUE TITLE
Is mentioned FPS for model inference only or for model inference +postprocessing?

### ISSUE THREAD

**Issue by s7s** [tensorlayer/hyperpose#197]
"We are improving the performance of the engine. Initial benchmark results for running the full OpenPose model are as follows. On Jetson TX2, the inference speed is 13 frames / second (the mobilenet variant is even faster). On Jetson TX1, the speed is 10 frames / second. On Titan 1050, the speed is 38 frames / second."

Is mentioned FPS for model inference only or for model inference +postprocessing?

**Comment by daylightsaving2017** [comment]
@s7s @luomai I am also interested in the timing method of this algorithm. I found the post-processing was very time-consuming, which made the evalution program not be able to reach that high fps(38fps-1050Ti). Could you please give some hints for us?
