### ISSUE TITLE
trained model mobilenet

### ISSUE THREAD

**Issue by zhangxiaopang88** [tensorlayer/hyperpose#202]
Hello, Are you test  on the Mobilenet?How did it turn out? can you provide a trained mobilenet network?

**Comment by bela127** [comment]
Take a look at my answer at:
#201

and the issue on training from scratch from:
#199

**Comment by bela127** [comment]
another solution would be to load the weights of only the mobilenet classifikator into the open-pose net, so you only have to train the last layers (stages) of your model.

you could just use the mobilenet weights here:
https://github.com/tensorlayer/pretrained-models/tree/master/models

I cloned and changed the code a bit, so this can be done easily with the training config
https://github.com/bela127/openpose-plus/blob/master/train.py
