### ISSUE TITLE
"TensorLayer does not support Tensorflow version older than 2.0.0

### ISSUE THREAD

**Issue by sfssqs** [tensorlayer/hyperpose#203]
hi author, i run 
# python3 train.py
after installed the requierment, but only found an error，my tensorflow version is 2.0.0-alph0
 
-------------------------
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    import tensorlayer as tl
  File "/home/yons/.local/lib/python3.6/site-packages/tensorlayer/__init__.py", line 36, in <module>
    "TensorLayer does not support Tensorflow version older than 2.0.0.\n"
RuntimeError: TensorLayer does not support Tensorflow version older than 2.0.0.
Please update Tensorflow with:
 - `pip install --upgrade tensorflow`
 - `pip install --upgrade tensorflow-gpu`

**Comment by zsdonghao** [comment]
please downgrade Tensorlayer to 1.14

**Comment by infdahai** [comment]
I also encounter this problem. And I downgrade Tensorlayer to 1.10.0

**Comment by neherh** [comment]
Does anyone know if openpose-plus will be updated to accommodate for the most recent tensorlayer and tensorflow?

**Comment by zsdonghao** [comment]
The core team are now working hard on RL and NLP examples, it would be great to have someone to work on openpose-plus.

**Comment by neherh** [comment]
Alright. If you want, I can work on it then and get it working on TF 2.0

**Comment by tony2278** [comment]
tensorflow-gpu  : 1.9.0

**"TensorLayer does not support Tensorflow version older than 2.0.0.\n"
RuntimeError: TensorLayer does not support Tensorflow version older than 2.0.0.**

AND I can not downgrade Tensorlayer to 1.14!

**Comment by Eva-Deng** [comment]
tensorflow:1.14.0

"TensorLayer does not support Tensorflow version older than 2.0.0.\n"
RuntimeError: TensorLayer does not support Tensorflow version older than 2.0.0.

When I downgrade Tensorlayer, the following error occurred:
zlib.error: Error -3 while decompressing data: invalid code length set

**Comment by zsdonghao** [comment]
TensorLayer 2.0+ needs TensorFlow 2.0+, this project uses TensorLayer 1.X and TensorFlow 1.12

**Comment by t126tank** [comment]
Hi guys,

I am using win10 with python 3.6, when I downgraded tensorlayer to 1.14 by
> py -3 -m pip install --upgrade tensorlayer==1.14

Here comes the errors:
----------------------------------------------------------------------------------------------
  ERROR: Could not find a version that satisfies the requirement tensorlayer==1.14 (from versions: 1.2, 1.2.1, 1.2.2, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.7.0, 1.7.1, 1.7.2rc0, 1.7.2, 1.7.3, 1.7.4, 1.8.0rc0, 1.8.0, 1.8.1, 1.8.2, 1.8.3rc0, 1.8.3, 1.8.4rc0, 1.8.4rc1, 1.8.4, 1.8.5rc1, 1.8.5rc2, 1.8.5, 1.8.6rc0, 1.8.6rc1, 1.8.6rc2, 1.8.6rc3, 1.8.6rc4, 1.8.6rc5, 1.8.6rc6, 1.9.0, 1.9.1, 1.10.1rc0, 1.10.1, 1.11.0rc0, 1.11.0, 1.11.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0)
ERROR: No matching distribution found for tensorlayer==1.14

Any ideas? Thanks in advance!
