### ISSUE TITLE
Performance issue on xavier

### ISSUE THREAD

**Issue by savan77** [tensorlayer/hyperpose#211]
Hi,

I am trying to run live-camera.sh on xavier which is faster than TX2 and TX. But I am getting 14 FPS around, which I don't think as a good number since you have reported higher FPS on TX2.

I also tried to check Tensor Core usage but it didn't report any events. So most probably it didn't use any Cores. I compiled the code using `make pack`. Then, ran the script.

Can you please comment on this performance issue? It would also be great if you can comment on how to run provided model with TensorRT in Python.

Thanks

**Comment by VolcanoGao** [comment]
Hello, may I ask have you solved the problem,I've had this problem recently.Thank you very much!
