### ISSUE TITLE
[SOLVED] ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

### ISSUE THREAD

**Issue by oneoyz** [tensorlayer/hyperpose#216]
The requirement of numpy's version is >=1.14,<1.16, but there is a ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject.

Finally I upgrade the numpy to 1.16.1, and it works.

**Comment by yogeshnile** [comment]
It's Not Work

**Comment by yogeshnile** [comment]
i am update numpy to 1.16.1 and run programme but not any change in error

**Comment by oneoyz** [comment]
> i am update numpy to 1.16.1 and run programme but not any change in error

There might be two reasons: Numpy version is too high or too low, You can try to upgrade to a later version or the latest version. Or downgrade your NumPy to a previous version.
