### ISSUE TITLE
Paf process 

### ISSUE THREAD

**Issue by ivanhc** [tensorlayer/hyperpose#217]
Hi, 

I think there is a possible bug in the code in the paf.cpp file line 216
                        if (hr1.parts[i].id > 0 && hr2.parts[i].id > 0) {

If I understand correctly the getHumans algorithm: 
 - Check all the human that touches the connection to evaluate
 - If doesnt exist human 
         - Create a new human with the connection
 - If exist one human 
         - Check if already exist the keypoint in the human 
               - in case doesnt exist : add keypoint to human  
 - if exist more than one human 
         - Check if both human are the same human
                   if (hr1.parts[i].id > 0 && hr2.parts[i].id > 0)
         - Case they are the same human : join both humans
         - Case are different human : add keypoint to human

The condition should be : 
            - if (hr1.parts[i].id > -1 && hr2.parts[i].id > -1)
            - instead of if (hr1.parts[i].id > 0 && hr2.parts[i].id > 0)
because you want to check the complete human otherwise you are missing the nose (0 keypoint)

Ivan

**Comment by luomai** [comment]
@ivanhc Thanks for reporting this. We appreciate this.

@lgarithm Do you have some time to look at this?
