### ISSUE TITLE
How to test openpose-plus on Nvidia Jetson TX2?

### ISSUE THREAD

**Issue by bhooshan-supe-gmail** [tensorlayer/hyperpose#226]

**Comment by bhooshan-supe-gmail** [comment]
For one of our projects we are using openpose on Nvidia Jetson TX2.
But the frame rate is not good enough. 
So wanted to try out openpose-plus.
On our hardware we have :- 
1.1. CUDA 10.0
1.2. OpenCV 4.1.0
1.3. Python 3.6
So kindly let us know how I can try openpose-plus.

**Comment by zsdonghao** [comment]
please follow the readme

**Comment by bhooshan-supe-gmail** [comment]
I have gone through the readme and have followed the instructions.
But when I execute "./scripts/live-camera.sh" :-
1.1. I see an window opened with black rectangle where I should see video
1.2. But when I select that window with mouse and press "Q" on key board
1.3. The black window is updated with the first frame from web-camera
1.4. But after that the frame is not update
1.5. I see following log
bhooshansupe@ARC-Supe-2647:~/WORK/PICK_AND_GO/BUILD/Code/openpose-plus (master)$ ./scripts/live-camera.sh
mkdir -p /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux
cd /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux; cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Release  /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus
-- Found CUDA: /usr/local/cuda (found suitable exact version "10.0") 
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux
make -C /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux -j 48
make[1]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[2]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[  2%] Performing update step for 'stdtensor-repo'
[  5%] Performing update step for 'stdtracer-repo'
[  8%] Performing configure step for 'stdtracer-repo'
[ 11%] Performing configure step for 'stdtensor-repo'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtensor-repo-build
[ 14%] Performing build step for 'stdtensor-repo'
make[4]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtensor-repo-build'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build
make[4]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtensor-repo-build'
[ 17%] Performing build step for 'stdtracer-repo'
make[4]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
[ 20%] Performing install step for 'stdtensor-repo'
make[4]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtensor-repo-build'
make[5]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
make[6]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
make[6]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
[100%] Built target stdtracer
make[5]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
make[4]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtensor.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/std_tensor.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/std_cuda_tensor.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/std_shape.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtensor
make[4]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtensor-repo-build'
[ 23%] Performing install step for 'stdtracer-repo'
make[4]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
[ 26%] Completed 'stdtensor-repo'
make[5]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
make[6]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[6]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
[ 35%] Built target stdtensor-repo
[100%] Built target stdtracer
make[5]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
Install the project...
-- Install configuration: ""
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/lib/libstdtracer.a
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtracer_simple
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/stdtracer_simple_ctx.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/stdtracer_stack_ctx.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/stdtracer_base.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/stdtracer_scope.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/bits/stdtracer_log_ctx.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtracer
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtracer_disable
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtracer.hpp
-- Up-to-date: /home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/./include/stdtracer_stack
make[4]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/3rdparty/src/stdtracer-repo-build'
[ 38%] Completed 'stdtracer-repo'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[ 47%] Built target stdtracer-repo
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[ 47%] Built target all-external-projects
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[ 58%] Built target openpose-plus
[ 67%] Built target helpers
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[ 73%] Built target stream-detetor
[ 82%] Built target pose-detetor
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Entering directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[3]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
[ 88%] Built target example-live-camera
[ 94%] Built target example-stream-detector
[100%] Built target example-batch-detector
make[2]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'
make[1]: Leaving directory '/home/bhooshansupe/WORK/PICK_AND_GO/BUILD/Code/openpose-plus/cmake-build/Linux'

binding 0: name: image type0(3, 256, 384)
binding 1: name: outputs/paf type0(38, 32, 48)
binding 2: name: outputs/conf type0(19, 32, 48)
#0 :: 960 x 1280
selected 36 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 0-th image
#1 :: 960 x 1280
#2 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
#3 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
#4 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
selected 31 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 1-th image
#5 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
selected 26 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 2-th image
#6 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
selected 34 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 3-th image
#7 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
selected 34 peaks with value > 0.050000
got 0 incomplete humans
got 0 humans
got 0 humnas from 4-th image
#8 :: 960 x 1280
QObject::startTimer: Timers cannot be started from another thread
^C
bhooshansupe@ARC-Supe-2647:~/WORK/PICK_AND_GO/BUILD/Code/openpose-plus (master)$ `
`

**Comment by MPMongrel** [comment]
Assuming that you have the same setup as I do (somewhat recent JetPack), you will be using TensorRT 5, which isn't really supported in the demo. However, for me that was fixed by modifying the source code as described at the end of the this comment (changing stream_detector.cpp):
https://github.com/tensorlayer/openpose-plus/issues/182#issuecomment-490837621
