### ISSUE TITLE
Acknowledgement of TensorLayer, how?

### ISSUE THREAD

**Issue by mayaghaei** [tensorlayer/hyperpose#246]
Hi all,

In the License section, it is mentioned that to use this code in a commercial setting we are required to acknowledge TensorLayer in the project website or article. I have two questions:

1- To acknowledge TensorLayer, is it enough to name and thank TensorLayer and this code somewhere in the project documentation?
2- I am wondering how does exactly acknowledgment work if there won't be any public output of the project anywhere? I mean no publicly available project page, publication, or software?

Thanks!

**Comment by zsdonghao** [comment]
Hi, you can cite the paper in your publication and put TensorLayer logo on your webpage page.

```
@article{tensorlayer2017,
    author  = {Dong, Hao and Supratak, Akara and Mai, Luo and Liu, Fangde and Oehmichen, Axel and Yu, Simiao and Guo, Yike},
    journal = {ACM Multimedia},
    title   = {{TensorLayer: A Versatile Library for Efficient Deep Learning Development}},
    url     = {http://tensorlayer.org},
    year    = {2017}
}
```
