### ISSUE TITLE
NvUffParser.h: No such file or directory  #include <NvUffParser.h>

### ISSUE THREAD

**Issue by shahram7** [tensorlayer/hyperpose#247]
hi guys,

I'm a beginner and i'm trying to install openpose-plus.
I have already installed openpose and try to do the same here.

```
git clone https://github.com/tensorlayer/openpose-plus.git
cd openpose-plus
mkdir build && cd build
cmake ..
make all -j12
```
but I get the following error after the fifth step:

```
/home/shahram/hd/openpose-plus/src/uff_runner.cpp:16:10: fatal error: NvUffParser.h: No such file or directory
 #include <NvUffParser.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/openpose-plus.dir/build.make:108: recipe for target 'CMakeFiles/openpose-plus.dir/src/uff_runner.cpp.o' failed
make[2]: *** [CMakeFiles/openpose-plus.dir/src/uff_runner.cpp.o] Error 1
CMakeFiles/Makefile2:339: recipe for target 'CMakeFiles/openpose-plus.dir/all' failed
make[1]: *** [CMakeFiles/openpose-plus.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
```

```
shahram@ubuntuserver:~$ pip3 freeze
absl-py==0.9.0
appdirs==1.4.3
apturl==0.5.2
asn1crypto==0.24.0
astor==0.8.1
beautifulsoup4==4.6.0
Brlapi==0.6.6
certifi==2020.4.5.1
chardet==3.0.4
cloudpickle==1.3.0
command-not-found==0.3
cryptography==2.1.4
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.16
decorator==4.4.2
defer==1.0.6
distlib==0.3.0
distro-info===0.18ubuntu0.18.04.1
easydict==1.9
filelock==3.0.12
gast==0.3.3
google-pasta==0.2.0
grpcio==1.28.1
h5py==2.10.0
html5lib==0.999999999
httplib2==0.9.2
hyperdash==0.15.3
idna==2.9
imageio==2.8.0
importlib-metadata==1.6.0
importlib-resources==1.4.0
ipython==5.5.0
ipython-genutils==0.2.0
joblib==0.14.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.2.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
leveldb==0.1
louis==3.5.0
lxml==4.5.0
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==3.2.1
MarkupSafe==1.0
matplotlib==3.2.1
netifaces==0.10.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
numexpr==2.6.4
numpy==1.18.3
oauth==1.0.1
olefile==0.45.1
opencv-python==4.2.0.34
pandas==0.22.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==7.1.1
progressbar2==3.51.0
prompt-toolkit==1.0.15
protobuf==3.11.3
pycairo==1.16.2
pycocotools==2.0.0
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.4.7
pyRFC3339==1.0
pyserial==3.4
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
python-debian==0.1.32
python-gflags==1.5.1
python-slugify==4.0.0
python-utils==2.4.0
pytz==2018.3
PyWavelets==1.1.1
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.23.0
requests-unixsocket==0.1.5
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
screen-resolution-extra==0.0.0
SecretStorage==2.3.1
simplegeneric==0.8.1
simplejson==3.13.2
six==1.14.0
ssh-import-id==5.7
system-service==0.3
systemd-python==234
tables==3.4.2
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorlayer==2.2.1
termcolor==1.1.0
text-unidecode==1.3
tqdm==4.45.0
traitlets==4.3.2
tzlocal==1.5.1
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.9
usb-creator==0.3.3
virtualenv==20.0.18
wadllib==1.3.2
wcwidth==0.1.7
webencodings==0.5
Werkzeug==1.0.1
wrapt==1.12.1
xkit==0.0.0
zipp==3.1.0
zope.interface==4.3.2
```

**Comment by ganler** [comment]
Hi @shahram7 , this header file is from TensorRT. You must have it installed in advance if you want to build the cplusplus library. 

Maybe this link could help: [LINK](https://github.com/NVIDIA/TensorRT).

Also, see other dependencies [here](https://github.com/tensorlayer/openpose-plus/blob/master/doc/markdown-doc/cpp-inference.md).

**Comment by shahram7** [comment]
> Hi @shahram7 , this header file is from TensorRT. You must have it installed in advance if you want to build the cplusplus library.
> 
> Maybe this link could help: [LINK](https://github.com/NVIDIA/TensorRT).
> 
> Also, see other dependencies [here](https://github.com/tensorlayer/openpose-plus/blob/master/doc/markdown-doc/cpp-inference.md).

Hi @ganler ,

i have downloaded and installed tensorRT as deb file from nvidia site Nevertheless I get this error message when I enter the "make all -j12".
Is it possible to install openpose-plus without a c++ library?

best regards

**Comment by lgarithm** [comment]
@shahram7 currently it's not possible to install openpose-plus without building the C++ library.
Could you share some more detailed step about how you installed tensortRT?
Note that you need to register and login to download the correct tensortRT deb package.
```
102e37c783fa72b65d83ba949a09e35ee5096678  nv-tensorrt-repo-ubuntu1804-cuda10.2-trt7.0.0.11-ga-20191216_1-1_amd64.deb
```
after install `nv-tensorrt-repo`, you need to run `apt update && apt install -y libnvinfer-dev libnvparsers-dev`

**Comment by shahram7** [comment]
Hi @lgarithm ,
first of all I thank you for your answer and your time.
Right. I opened an account at Nvidia and downloaded this Deb file.

`
Name: nv-tensorrt-repo-ubuntu1804-cuda10.2-trt7.0.0.11-ga-20191216_1-1_amd64.deb
Size: 978825220 bytes (933 MiB)
CRC32: D66162D6
CRC64: F3754B0AF7C98199
SHA256: E061633F076A9AE23778E05CD7CB0F37442178B35AE4100BA7A37EF57B43B80C
SHA1: 102E37C783FA72B65D83BA949A09E35EE5096678
BLAKE2sp: 0183DC40C0CB0FB9286D3D622103660134C122C1CA34EC44FF118E4881FF6F27
`
then I transferred the file via WinSCP to my server and installed it.

I just didn't make these commands.
>  after install `nv-tensorrt-repo`, you need to run `apt update && apt install -y libnvinfer-dev libnvparsers-dev`

which helped me and my old problem has now been solved.

but I'm getting these messages now

`
~/hd/openpose-plus/build$ make all -j12
Scanning dependencies of target stdtensor-repo
Scanning dependencies of target stdtracer-repo
[  2%] Performing update step for 'stdtracer-repo'
[  5%] Performing update step for 'stdtensor-repo'
[  8%] Performing configure step for 'stdtracer-repo'
[ 10%] Performing configure step for 'stdtensor-repo'
-- stdtensor-repo configure command succeeded.  See also /home/shahram/hd/openpose-plus/3rdparty/src/stdtensor-repo-stamp/stdtensor-repo-configure-*.log
-- stdtracer-repo configure command succeeded.  See also /home/shahram/hd/openpose-plus/3rdparty/src/stdtracer-repo-stamp/stdtracer-repo-configure-*.log
[ 13%] Performing build step for 'stdtensor-repo'
[ 16%] Performing build step for 'stdtracer-repo'
[ 18%] Performing install step for 'stdtensor-repo'
[100%] Built target stdtracer
[ 21%] Performing install step for 'stdtracer-repo'
-- stdtensor-repo install command succeeded.  See also /home/shahram/hd/openpose-plus/3rdparty/src/stdtensor-repo-stamp/stdtensor-repo-install-*.log
[ 24%] Completed 'stdtensor-repo'
[ 32%] Built target stdtensor-repo
-- stdtracer-repo install command succeeded.  See also /home/shahram/hd/openpose-plus/3rdparty/src/stdtracer-repo-stamp/stdtracer-repo-install-*.log
[ 35%] Completed 'stdtracer-repo'
[ 43%] Built target stdtracer-repo
Scanning dependencies of target all-external-projects
[ 43%] Built target all-external-projects
Scanning dependencies of target openpose-plus
Scanning dependencies of target helpers
[ 45%] Building CXX object CMakeFiles/helpers.dir/examples/input.cpp.o
[ 48%] Building CXX object CMakeFiles/helpers.dir/examples/vis.cpp.o
[ 51%] Building CXX object CMakeFiles/helpers.dir/examples/thread_pool.cpp.o
[ 54%] Building CXX object CMakeFiles/openpose-plus.dir/src/cudnn.cpp.o
[ 56%] Building CXX object CMakeFiles/openpose-plus.dir/src/uff_runner.cpp.o
[ 59%] Building CXX object CMakeFiles/openpose-plus.dir/src/paf.cpp.o
/home/shahram/hd/openpose-plus/src/uff_runner.cpp: In function ‘nvinfer1::ICudaEngine* loadModelAndCreateEngine(const char*, int, nvuffparser::IUffParser*, bool)’:
/home/shahram/hd/openpose-plus/src/uff_runner.cpp:83:78: warning: ‘virtual nvinfer1::INetworkDefinition* nvinfer1::IBuilder::createNetwork()’ is deprecated [-Wdeprecated-declarations]
     destroy_ptr<nvinfer1::INetworkDefinition> network(builder->createNetwork());
                                                                              ^
In file included from /home/shahram/hd/openpose-plus/src/uff_runner.cpp:15:0:
/usr/include/x86_64-linux-gnu/NvInfer.h:6326:58: note: declared here
     TRT_DEPRECATED virtual nvinfer1::INetworkDefinition* createNetwork() TRTNOEXCEPT = 0;
                                                          ^~~~~~~~~~~~~
/home/shahram/hd/openpose-plus/src/uff_runner.cpp:90:35: warning: ‘virtual void nvinfer1::IBuilder::setHalf2Mode(bool)’ is deprecated [-Wdeprecated-declarations]
         builder->setHalf2Mode(true);  // For older version of tensorRT
                                   ^
In file included from /home/shahram/hd/openpose-plus/src/uff_runner.cpp:15:0:
/usr/include/x86_64-linux-gnu/NvInfer.h:6382:33: note: declared here
     TRT_DEPRECATED virtual void setHalf2Mode(bool mode) TRTNOEXCEPT = 0;
                                 ^~~~~~~~~~~~
/home/shahram/hd/openpose-plus/src/uff_runner.cpp:97:45: warning: ‘virtual nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildCudaEngine(nvinfer1::INetworkDefinition&)’ is deprecated [-Wdeprecated-declarations]
     return builder->buildCudaEngine(*network);
                                             ^
In file included from /home/shahram/hd/openpose-plus/src/uff_runner.cpp:15:0:
/usr/include/x86_64-linux-gnu/NvInfer.h:6461:51: note: declared here
     TRT_DEPRECATED virtual nvinfer1::ICudaEngine* buildCudaEngine(
                                                   ^~~~~~~~~~~~~~~
/home/shahram/hd/openpose-plus/src/uff_runner.cpp: In function ‘nvinfer1::ICudaEngine* create_engine(const string&, const input_info_t&, const std::vector<std::__cxx11::basic_string<char> >&, int, bool)’:
/home/shahram/hd/openpose-plus/src/uff_runner.cpp:113:56: warning: ‘DimsCHW’ is deprecated [-Wdeprecated-declarations]
             nvinfer1::DimsCHW(dims[0], dims[1], dims[2]),
                                                        ^
In file included from /home/shahram/hd/openpose-plus/src/uff_runner.cpp:15:0:
/usr/include/x86_64-linux-gnu/NvInfer.h:206:22: note: declared here
 class TRT_DEPRECATED DimsCHW : public Dims3
                      ^~~~~~~
[ 62%] Linking CXX static library libhelpers.a
[ 62%] Built target helpers
Scanning dependencies of target test-thread-pool
[ 64%] Building CXX object CMakeFiles/test-thread-pool.dir/examples/test_thread_pool.cpp.o
[ 67%] Linking CXX static library libopenpose-plus.a
[ 67%] Built target openpose-plus
Scanning dependencies of target stream-detetor
Scanning dependencies of target pose-detetor
[ 70%] Building CXX object CMakeFiles/stream-detetor.dir/examples/stream_detector.cpp.o
[ 72%] Building CXX object CMakeFiles/pose-detetor.dir/examples/input.cpp.o
[ 75%] Building CXX object CMakeFiles/pose-detetor.dir/examples/pose_detector.cpp.o
[ 78%] Linking CXX executable test-thread-pool
[ 78%] Built target test-thread-pool
[ 81%] Linking CXX static library libstream-detetor.a
[ 81%] Built target stream-detetor
Scanning dependencies of target example-live-camera
Scanning dependencies of target example-stream-detector
[ 83%] Building CXX object CMakeFiles/example-stream-detector.dir/examples/example_stream_detector.cpp.o
[ 86%] Building CXX object CMakeFiles/example-live-camera.dir/examples/example_live_camera.cpp.o
[ 89%] Linking CXX static library libpose-detetor.a
[ 89%] Built target pose-detetor
Scanning dependencies of target example-batch-detector
[ 91%] Building CXX object CMakeFiles/example-batch-detector.dir/examples/example_batch_detector.cpp.o
[ 94%] Linking CXX executable example-batch-detector
/usr/bin/ld: warning: libcudart.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, may conflict with libcudart.so.10.1
/usr/bin/ld: warning: libnvrtc.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLogSize@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTX@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCreateProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCompileProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLog@libnvrtc.so.10.2'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetErrorString@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetLoweredName@libnvrtc.so.10.2'
collect2: error: ld returned 1 exit status
CMakeFiles/example-batch-detector.dir/build.make:112: recipe for target 'example-batch-detector' failed
make[2]: *** [example-batch-detector] Error 1
CMakeFiles/Makefile2:369: recipe for target 'CMakeFiles/example-batch-detector.dir/all' failed
make[1]: *** [CMakeFiles/example-batch-detector.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Linking CXX executable example-stream-detector
/usr/bin/ld: warning: libcudart.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, may conflict with libcudart.so.10.1
/usr/bin/ld: warning: libnvrtc.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLogSize@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTX@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCreateProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCompileProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLog@libnvrtc.so.10.2'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetErrorString@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetLoweredName@libnvrtc.so.10.2'
collect2: error: ld returned 1 exit status
CMakeFiles/example-stream-detector.dir/build.make:112: recipe for target 'example-stream-detector' failed
make[2]: *** [example-stream-detector] Error 1
CMakeFiles/Makefile2:117: recipe for target 'CMakeFiles/example-stream-detector.dir/all' failed
make[1]: *** [CMakeFiles/example-stream-detector.dir/all] Error 2
[100%] Linking CXX executable example-live-camera
/usr/bin/ld: warning: libcudart.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, may conflict with libcudart.so.10.1
/usr/bin/ld: warning: libnvrtc.so.10.2, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so, not found (try using -rpath or -rpath-link)
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcDestroyProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCompileProgram@libnvrtc.so.10.2'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libnvinfer.so: undefined reference to `nvrtcVersion@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTX@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcCreateProgram@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcAddNameExpression@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetPTXSize@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLog@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetLoweredName@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetErrorString@libnvrtc.so.10.2'
//usr/lib/x86_64-linux-gnu/libmyelin.so.1: undefined reference to `nvrtcGetProgramLogSize@libnvrtc.so.10.2'
collect2: error: ld returned 1 exit status
CMakeFiles/example-live-camera.dir/build.make:112: recipe for target 'example-live-camera' failed
make[2]: *** [example-live-camera] Error 1
CMakeFiles/Makefile2:399: recipe for target 'CMakeFiles/example-live-camera.dir/all' failed
make[1]: *** [CMakeFiles/example-live-camera.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
`
I have not installed a camera yet and would like to start with Examples.

best regards
