### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/hyperpose#248]
-  [x] resolve conflict on branch https://github.com/tensorlayer/openpose-plus/commits/refactorization
- [x] create pull request
- [x] update docs
- ...
- [ ] use gtest for unit test (@lgarithm)
- [ ] use CMake instead of Make as the default build tool (@lgarithm)

**Comment by ganler** [comment]
The newest PR is available on https://github.com/tensorlayer/openpose-plus/pull/249. :-)

**Comment by ganler** [comment]
v2 beta released!

About docs:
- [ ] Add tutorials and python API to the documents.
- [ ] Deploy new documents.

**Comment by ganler** [comment]
@lgarithm Could you remove / update old files in our repo(e.g., docker/, Make*, configure)
