### ISSUE TITLE
Fixes for cmake build & compile errors on windows/visual c++ 142

### ISSUE THREAD

**Issue by korejan** [tensorlayer/hyperpose#251]
Hi I know a version 2.0 is currently being worked on but I've commited some changes in my fork that fixes cmake build issues & C++ compile errors for windows & visual c++ 2019 [here](https://github.com/korejan/openpose-plus/commit/85e0be0c1085b2e1954e6460a2a9589a72002718).

**Comment by ganler** [comment]
@korejan Hi, thanks for your commits. I think you can create a PR about the fixes. And the branch of newer version will actively take the changes of the master branch. :-)

**Comment by lgarithm** [comment]
@ganler you can try stdml/stdtracer@v0.2.1 in the new version:
https://github.com/stdml/stdtracer/commit/3426d52a87ea7e35495401cce777147a2eefe69e
which doesn't include `unistd.h` by default.

**Comment by ganler** [comment]
@lgarithm Hi, is the master branch using the v0.2.1?

**Comment by lgarithm** [comment]
@ganler the master branch of openpose-plus is using unversioned tag

https://github.com/tensorlayer/openpose-plus/blob/0e6afe3f64074710e2a44d1d4870063c23bdd15c/cmake/3rdparty.cmake#L15

**Comment by ganler** [comment]
@lgarithm Confirmed. I will have a try tomorrow. (Today I reinstalled my system)

**Comment by korejan** [comment]
This is still an issue with V2 plus additional new uses of std::to_string/max without including the apprioate headers. experimental/filesystem header is not in experimental anymore in C++17 and VC++ with C++17 mode gives this error message about that. I would submit a pull request but right now I can't clone the repo, I had to manually download a zip of the code.

**Comment by korejan** [comment]
When I update 3rdParty.cmake to use the latest release version of stdtracer (using the git tag ""v0.2.1" the stdtracker projects are uility projects and doesn't generate .lib file but the example projects try to link to to stdtracer.lib

**Comment by korejan** [comment]
I'm closing this as I've made a pull request [here](https://github.com/tensorlayer/hyperpose/pull/266)
