### ISSUE TITLE
why I have so low FPS?

### ISSUE THREAD

**Issue by lwcode** [tensorlayer/hyperpose#253]
I test it on Windows10+CUDA10.0+cudnn7.6+TensorRT7+opencv3.4, one 1080ti@E5-2620 v4, and run .\build\Release\example-stream-detector.exe --model_file=data\models\hao28-600000-256x384.uff  -input_height 256 -input_width 384 --image_files=xxx , the final ouput is:
// inferenced 1638 images of 256 x 384, took 124.27s, mean: 75.87ms, FPS: 13.180601, buffer size: 4, use f16: 1, gauss kernel size: 17

why the FPS just have 13.8? if I do not config the tensorRT with right way or others reason? use f16 or not is the same.

**Comment by lwcode** [comment]
by the way, the GPU is one 1080ti

**Comment by ganler** [comment]
Hi @lwcode 

In the master branch, only `example-batch-detector` is optimized with high throughput. To have a relatively better performance, you can try the following solutions:

* Use the codes in `refactorization` branch which will be released recently. (I can achieve over 100 FPS in the streaming example on my 1070TI)
* Re-execute the program. Often the first execution(cold start) tends to be 2~5x slower.
* Use `example-batch-detector`.

Please feel to tell your results in your following attempts. GOOD LUCK :-)

**Comment by lwcode** [comment]
> Hi @lwcode
> 
> In the master branch, only `example-batch-detector` is optimized with high throughput. To have a relatively better performance, you can try the following solutions:
> 
> * Use the codes in `refactorization` branch which will be released recently. (I can achieve over 100 FPS in the streaming example on my 1070TI)
> * Re-execute the program. Often the first execution(cold start) tends to be 2~5x slower.
> * Use `example-batch-detector`.
> 
> Please feel to tell your results in your following attempts. GOOD LUCK :-)

Thanks for your reply, waiting for the new branch "refactorization". I modify the input images code in  example-batch-detector  like example-stream-detector, and use the same command: .\build\Release\example-batch-detector.exe --model_file=data\models\hao28-600000-256x384.uff -input_height 256 -input_width 384 --image_files=xxx , result was more faster, but not good: // inferenced 1638 images of 256 x 384, took 98.68s, mean: 60.25ms, FPS: 16.598562, batch size: 8, use f16: 0, gauss kernel size: 17, this is the third times running, if I have make some hidden error operation?

**Comment by ganler** [comment]
Hi @lwcode , I don't know if this is a performance issue related to platforms(I tested the performance on Ubuntu18.04 2 months ago and got 30~50 FPS by running the default command. 

I think we will release the new version in the next 2 days and I'll inform you then.

You can also just `git checkout refactorization` and run the new examples to see if the performance gets better.

**Comment by ganler** [comment]
Hi @lwcode , we released our v2. Check it out on our master branch.

**Comment by ganler** [comment]
I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.

Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)

@lgarithm Should we force the optimization flag for MSVC?

**Comment by korejan** [comment]
There are default cmake optimation flags used for vc++ in release builds, but not fast maths (which is **/fp:fast** for vc++) and using intrinsic functions ( **/Oi** ), you can set this yourself of-course and I noticed a big improvement additionally using /Oi /fp:fast /arch:AVX2

I recently i've spent a lot of time analysing and optimizintg V1 in my local repo. I want to make a post about that plus various other things I've noticed at some point but seeing as V2 is now in master I'm going to look into that first.

For now I'll briefly say that the most costly function is the CPU based max pooling (same_max_pool_3x3), there's a parameter you can set to use GPU based maxing pooling which is much faster.

**Comment by korejan** [comment]
> 
> 
> I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.
> 
> Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)
> 
> @lgarithm Should we force the optimization flag for MSVC?

There are default cmake optimation flags used for vc++ in release builds, but not fast maths (which is **/fp:fast** for vc++) and using intrinsic functions ( **/Oi** ), you can set this yourself of-course and I noticed a big improvement additionally using /Oi /fp:fast /arch:AVX2

I recently i've spent a lot of time analysing and optimizintg V1 in my local repo. I want to make a post about that plus various other things I've noticed at some point but seeing as V2 is now in master I'm going to look into that first.

For now I'll briefly say that the most costly function is the CPU based max pooling (same_max_pool_3x3), there's a parameter you can set to use GPU based maxing pooling which is much faster.

**Comment by lgarithm** [comment]
I think we should make `-DCMAKE_BUILD_TYPE=RELEASE` the default.

**Comment by ganler** [comment]
> I think we should make `-DCMAKE_BUILD_TYPE=RELEASE` the default.

I added this in my new PR.

**Comment by lwcode** [comment]
> I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.
> 
> Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)
> 
> @lgarithm Should we force the optimization flag for MSVC?

I build v2 with release mode(same as other pre-branch I tested), and using intrinsic functions /O2, I can run project "example.operator_api_batched_images" and get "100 images got processed. FPS = 36.4951" more faster than before, FPS similar to Openpose with option "-net_resolution "-1x208"". By the way, when I use project "example.stream_api_video", the output is:
[OpenPose-Plus::EXAMPLE] Input video name: ../data/media/video.avi
[OpenPose-Plus::EXAMPLE] Output video name: output_video.avi
[OpenPose-Plus::EXAMPLE] Input Frame: Size@[1280 x 720]Count@205
ERROR: Tensor image cannot be both input and output
queue size overfloor, max size = 128
Currently: size/capacity: 128/128, space needed: 8

how to fix them?

**Comment by lwcode** [comment]
> > I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.
> > Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)
> > @lgarithm Should we force the optimization flag for MSVC?
> 
> There are default cmake optimation flags used for vc++ in release builds, but not fast maths (which is **/fp:fast** for vc++) and using intrinsic functions ( **/Oi** ), you can set this yourself in cmake of-course and I noticed a big improvement additionally using /Oi /fp:fast /arch:AVX2
> 
> I've recently i've spent a fair amount of time analysing and optimizintg V1 in my local repo. I want to make a post about that plus various other things I've noticed at some point but seeing as V2 is now in master I'm going to look into that first.
> 
> For now I'll briefly say that the most costly function is the CPU based max pooling (same_max_pool_3x3), there's a parameter you can set to use GPU based maxing pooling which is much faster. There are some easy ways to make the CPU based max pooling much faster but it's a bit of brute force optimization.
> 
> @ganler

Thanks for reply, I test it with options "/O2" or "/O2 /fp:fast /arch:AVX2" or "/O2 /fp:fast" or "/O2 /arch:AVX2", It doesn't seem to be different on my machine

**Comment by ganler** [comment]
> > I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.
> > Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)
> > @lgarithm Should we force the optimization flag for MSVC?
> 
> I build v2 with release mode(same as other pre-branch I tested), and using intrinsic functions /O2, I can run project "example.operator_api_batched_images" and get "100 images got processed. FPS = 36.4951" more faster than before, FPS similar to Openpose with option "-net_resolution "-1x208"". By the way, when I use project "example.stream_api_video", the output is:
> [OpenPose-Plus::EXAMPLE] Input video name: ../data/media/video.avi
> [OpenPose-Plus::EXAMPLE] Output video name: output_video.avi
> [OpenPose-Plus::EXAMPLE] Input Frame: Size@[1280 x 720]Count@205
> ERROR: Tensor image cannot be both input and output
> queue size overfloor, max size = 128
> Currently: size/capacity: 128/128, space needed: 8
> 
> how to fix them?

Hi, this is not an error. The `ERROR` is produced by TensorRT but you can ignore it. And the queue size overflow is also not an error. It is telling you the queue is full and waiting to be poped.

You can wait a little longer and you can get the results.

And I tested the master branch again but didn't find out any problems.

![Screenshot from 2020-06-04 13-20-53](https://user-images.githubusercontent.com/38074777/83717868-57e93e00-a666-11ea-835e-6de9b95f2126.png)

![Screenshot from 2020-06-04 13-19-27](https://user-images.githubusercontent.com/38074777/83717890-65062d00-a666-11ea-91fe-50f8dddd7216.png)

![Screenshot from 2020-06-04 13-20-17](https://user-images.githubusercontent.com/38074777/83717897-6a637780-a666-11ea-992d-e6d5c20f2eef.png)

To solve your questions:

1. I'll try to make a best practice on the Windows platform.
2. I don't know if it is a problem of test images. (Have you tried the default images? Or is it because your input images is of very high resolution?)
3. And I noticed that you're giving 100 images to example.operator_api_batched_images. `example.operator_api_batched_images` will make all your inputs into one batch will may involve in higher GPU memory occupation. Did you try with a small number of images?

A big thank for your feedbacks. I think I will make the following changes:

- Avoid strange logs to users.
- Create example to support a big sequence of images efficiently.
- Try to build the project on Windows to tune its performance.

**Comment by lwcode** [comment]
> > > I also noticed that the low performance may come from not setting the optimization flags. I am not sure if you enabled that.
> > > Try `cmake .. -DCMAKE_BUILD_TYPE=RELEASE` on windows. (gcc/clang will use the `-Ofast -march=native` flag.)
> > > @lgarithm Should we force the optimization flag for MSVC?
> > 
> > 
> > I build v2 with release mode(same as other pre-branch I tested), and using intrinsic functions /O2, I can run project "example.operator_api_batched_images" and get "100 images got processed. FPS = 36.4951" more faster than before, FPS similar to Openpose with option "-net_resolution "-1x208"". By the way, when I use project "example.stream_api_video", the output is:
> > [OpenPose-Plus::EXAMPLE] Input video name: ../data/media/video.avi
> > [OpenPose-Plus::EXAMPLE] Output video name: output_video.avi
> > [OpenPose-Plus::EXAMPLE] Input Frame: Size@[1280 x 720]Count@205
> > ERROR: Tensor image cannot be both input and output
> > queue size overfloor, max size = 128
> > Currently: size/capacity: 128/128, space needed: 8
> > how to fix them?
> 
> Hi, this is not an error. The `ERROR` is produced by TensorRT but you can ignore it. And the queue size overflow is also not an error. It is telling you the queue is full and waiting to be poped.
> 
> You can wait a little longer and you can get the results.
> 
> And I tested the master branch again but didn't find out any problems.
> 
> ![Screenshot from 2020-06-04 13-20-53](https://user-images.githubusercontent.com/38074777/83717868-57e93e00-a666-11ea-835e-6de9b95f2126.png)
> 
> ![Screenshot from 2020-06-04 13-19-27](https://user-images.githubusercontent.com/38074777/83717890-65062d00-a666-11ea-91fe-50f8dddd7216.png)
> 
> ![Screenshot from 2020-06-04 13-20-17](https://user-images.githubusercontent.com/38074777/83717897-6a637780-a666-11ea-992d-e6d5c20f2eef.png)
> 
> To solve your questions:
> 
> 1. I'll try to make a best practice on the Windows platform.
> 2. I don't know if it is a problem of test images. (Have you tried the default images? Or is it because your input images is of very high resolution?)
> 3. And I noticed that you're giving 100 images to example.operator_api_batched_images. `example.operator_api_batched_images` will make all your inputs into one batch will may involve in higher GPU memory occupation. Did you try with a small number of images?
> 
> A big thank for your feedbacks. I think I will make the following changes:
> 
> * Avoid strange logs to users.
> * Create example to support a big sequence of images efficiently.
> * Try to build the project on Windows to tune its performance.

Hi, when it output  "queue size overfloor" , there is nothing else comming out, and the output_video.avi is empty. I have try many times.

I have tested the test images also, but have the similar result
this is the default GPU status:
![image](https://user-images.githubusercontent.com/12107803/83729077-ba980500-a679-11ea-9278-37d1e77e8652.png)
running the project:
![image](https://user-images.githubusercontent.com/12107803/83729222-f16e1b00-a679-11ea-8b81-25c340d9ac93.png)

for the testing images:
![image](https://user-images.githubusercontent.com/12107803/83729361-0ea2e980-a67a-11ea-9e48-89d27d0413b3.png)

**Comment by korejan** [comment]
@lwcode 
> 
> I build v2 with release mode(same as other pre-branch I tested), and using intrinsic functions /O2, 

/O2 is not the flag to enable intrinsic functions, O2 is level-2 optimiations and you shouldn't need to explicitlity set this because that is one of the default flags used for release builds (unless you're completely overriding the defaults). You need to use /Oi to enable intrincis functions, you can use them together, it's a seperate flag.

> 
> Thanks for reply, I test it with options "/O2" or "/O2 /fp:fast /arch:AVX2" or "/O2 /fp:fast" or "/O2 /arch:AVX2", It doesn't seem to be different on my machine

Does your CPU support AVX2 instructions? if not change it to the most recent SIMD instructions that CPU supports and as I said earlier **/Oi** is seperate flag, use that too.

You can also try enabling function inling **/Ob1** (Only __inline) or **/Ob2** (Any Suitable), I'm using the latter.

@ganler 

> Interestingly, I achieved
> 
>     * 80 FPS by manually using `-Ofast -march=native`.
> 

Those are not valid flags for Visual C++ and the compiler warns that it doesn't recoginize them too but as I said as long the default cmake cxx flags aren't being overridden /O2 will should be set for release builds (without debug) by default.

All of the extra flags I use in addition to the default flags set are:

CMAKE_CXX_FLAGS = defaults + **/std:c++17** (may/may not give perf benefits)

CMAKE_CXX_FLAGS_RELEASE = defaults + **/Oi /arch:AVX2 /fp:fast** // my cpu supports upto AVX2

*_LINKER_FLAGS_RELEASE = defaults + **/OPT:REF /OPT:ICF**

I haven't tried enabling whole program optimizations yet.

**Comment by lwcode** [comment]
> Hi, @lwcode
> Firstly thanks for your patience.
> 
> You can use `cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TRACE=ON` to trace the performance to see where it is slow.
> 
> Interestingly, I achieved
> 
> * 16 FPS processing the default test source using ` -DCMAKE_BUILD_TYPE=Debug` flag.
> * 80 FPS using `DCMAKE_BUILD_TYPE=Release` flag.
> * 80 FPS by manually using `-Ofast -march=native`.
> 
> And it seems to be a dead lock in the `stream api`, but I cannot reproduce it on Linux. I'll have a try on Monday using Windows(still the same machine).
> 
> You can do `./stream_api_XXX --logging` to see what is going on inside. It may a video utility dynamic library issue from OpenCV.
 trace on：
![image](https://user-images.githubusercontent.com/12107803/83787549-8c8ce200-a6c6-11ea-9f8d-84659a2a217a.png)
![image](https://user-images.githubusercontent.com/12107803/83787730-ceb62380-a6c6-11ea-840d-4df2a7de168b.png)

![image](https://user-images.githubusercontent.com/12107803/83787849-fe652b80-a6c6-11ea-9871-306d78b1f3eb.png)

and I have test it on Ubuntu18+CUDA10.0+cudnn7.6+TensorRT7, RTX 1050Ti@i5-4570，result is：
./example.stream_api_video：
[OpenPose-Plus::EXAMPLE] Input video name: ../data/media/video.avi
[OpenPose-Plus::EXAMPLE] Output video name: output_video.avi
[OpenPose-Plus::EXAMPLE] Input Frame: Size@[1280 x 720]Count@205
ERROR: Tensor image cannot be both input and output
queue size overfloor, max size = 128
Currently: size/capacity: 128/128, space needed: 1
queue size overfloor, max size = 128
Currently: size/capacity: 121/128, space needed: 14
queue size overfloor, max size = 128
Currently: size/capacity: 127/128, space needed: 44
205 images got processed in 4553.93 ms, FPS = 45.0161

./example.operator_api_batched_images：
20 images got processed. FPS = 41.9429

it works well.

**Comment by ganler** [comment]
@lwcode I can see that this is because the low performance of post processing.

Please confirm the following:
1. Did you REALLY enable the vector(e.g., AVX) instructions?
2. Have you built your OpenCV library with vector(e.g., AVX) instructions?

**Comment by lwcode** [comment]
> @lwcode
> 
> > I build v2 with release mode(same as other pre-branch I tested), and using intrinsic functions /O2,
> 
> /O2 is not the flag to enable intrinsic functions, O2 is level-2 optimizations and you shouldn't need to explicitlity set this because that is one of the default flags used for release builds (unless you're completely overriding the defaults). You need to use /Oi to enable intrincis functions, you can use them together, it's a seperate flag.
> 
> > Thanks for reply, I test it with options "/O2" or "/O2 /fp:fast /arch:AVX2" or "/O2 /fp:fast" or "/O2 /arch:AVX2", It doesn't seem to be different on my machine
> 
> Does your CPU support AVX2 instructions? if not change it to the most recent SIMD instructions that your CPU supports and as I said earlier **/Oi** is seperate flag, use that too.
> 
> You can also try enabling function inling **/Ob1** (Only __inline) or **/Ob2** (Any Suitable). **/Ob2** should be the default for release (without debug) builds.
> 
> @ganler
> 
> > Interestingly, I achieved
> > ```
> > * 80 FPS by manually using `-Ofast -march=native`.
> > ```
> 
> Those are not valid flags for Visual C++ and the compiler warns that it doesn't recoginize them too but as I said as long the default cmake cxx flags aren't being overridden /O2 will should be set for release builds (without debug) by default.
> 
> All of the extra flags I use in addition to the default flags set are:
> 
> CMAKE_CXX_FLAGS = defaults + **/std:c++17** (may/may not give perf benefits)
> 
> CMAKE_CXX_FLAGS_RELEASE = defaults + **/Oi /arch:AVX2 /fp:fast** // my cpu supports upto AVX2
> 
> *_LINKER_FLAGS_RELEASE = defaults + **/OPT:REF /OPT:ICF**
> 
> I haven't tried enabling whole program optimizations yet.

Thanks for your suggestion, I have check my cpu by cpu-z tool, it support AVX2 instructions :
![image](https://user-images.githubusercontent.com/12107803/83947062-4b700b80-a847-11ea-850d-90ec44354adf.png)

I use cmake-gui to configure the opencv and  hyperpose, and generate VS2017 solution.
for opencv, in cmake-gui:
![image](https://user-images.githubusercontent.com/12107803/83947170-08626800-a848-11ea-9eeb-0454b60624c8.png)
![image](https://user-images.githubusercontent.com/12107803/83947208-43649b80-a848-11ea-9daf-0e61e3aa96d9.png)
I even tried to set CPU_BASELINE and CPU_DISPATCH to AVX2 directly, there is no difference to use for hyperpose. 
I think I did some right configuration according to your advice, and the VS2017 whole solution property like this(project->property->C/C++->Command line):
![image](https://user-images.githubusercontent.com/12107803/83947524-1a450a80-a84a-11ea-921a-e81e9c4c6f8f.png)

something wrong with me?

@ganler

**Comment by ganler** [comment]
@lwcode Sorry for coming back so late. If you still remain interested, now we have a docker image now that you can take a try via docker in Windows to see if it is fast as we said.

**Comment by ganler** [comment]
We recently found a performance issue b.c. the thread pool by default allocates all threads. Now it is set with an upperbound. See https://github.com/tensorlayer/hyperpose/pull/366
