### ISSUE TITLE
train.py  imports openpose_plus package

### ISSUE THREAD

**Issue by t-wada** [tensorlayer/hyperpose#257]
train.py depends on openpose_plus, so the latest version of hyperpose will not be able to run the training.
Can I use a pre-trained model created with tag 1.0.0 of openpose_plus?

**Comment by ganler** [comment]
@t-wada Hi, the training module will be released soon. So I suggest you use a new version.
As for the inference module, we still support the exported Uff model that trained using openpose_plu 1.0.0.

**Comment by t-wada** [comment]
@ganler 
Thanks for your reply.
All right, I am looking forward to the release of the training module.

**Comment by ganler** [comment]
@t-wada Hi, you can take a look at our new training module now. We are still on the beta stage. So feel free to open new issues if you meet any problem. Closed.
