### ISSUE TITLE
hyperpose.git does not exist?

### ISSUE THREAD

**Issue by korejan** [tensorlayer/hyperpose#259]
I'm trying to clone the repo but git can't find the url
https://github.com/tensorlayer/hyperpose.git

**Comment by ganler** [comment]
Hi @korejan 

It is strange. I think I can clone it. 

![Screenshot from 2020-06-03 20-18-36](https://user-images.githubusercontent.com/38074777/83635902-97b51480-a5d7-11ea-9cb7-777fef9a01aa.png)

**Comment by korejan** [comment]
sorry I was doing somthing stupid, it's all fine now.
