### ISSUE TITLE
ppn.onnx file?

### ISSUE THREAD

**Issue by korejan** [tensorlayer/hyperpose#263]
I noticed a new commit that adds support for proposal networks, I wanted to try it out but i can't find the default model ppn.onnx where can i find this?

**Comment by ganler** [comment]
Hi, @korejan we have a model that was not well trained which has low precision in DNN stage and we are still working retraining. The bad model only has good precision when there's one person in the image. I can send you the bad model to your email if you got interested. And the bad precision won't hurt the speed of post-processing.

**Comment by korejan** [comment]
No problem I don't mind waiting for while but about single person tracking. Is there away to configure for single person only estimation? I have project where I'm only interested in the best performance (with a good accuracy) for a single person.

**Comment by ganler** [comment]
@korejan I think we can have "Single-Person Implementation of Post Processing". It can be super-efficient and easy to implement. We just need the feature maps containing the key-point confidence and select key points with the highest confidence. And the topology is fixed as there's only one person.

I'll have a try in the future.

**Comment by ganler** [comment]
@korejan Hi, the PPN model is released on the master branch.
