### ISSUE TITLE
git fetch fails on windows

### ISSUE THREAD

**Issue by korejan** [tensorlayer/hyperpose#268]
Hi, I'm trying to sync up but git fails on windows because a file called [ \ was added (and later removed)](https://github.com/tensorlayer/hyperpose/commit/868207aacb9b3448eae26a18b74cc92ca2e65c54)

Git error message:
remote: Total 26 (delta 15), reused 24 (delta 14), pack-reused 0        
**fatal: filename in tree entry contains backslash:** \ 
error: https://github.com/tensorlayer/hyperpose.git did not send all necessary objects

**Comment by lgarithm** [comment]
@luomai I think we need to squash the last 4 commits and do a force push to master.

**Comment by lgarithm** [comment]
@korejan we just force pushed master. Please let us know if it's still an issue.

**Comment by korejan** [comment]
@lgarithm still getting the same error, unable to fetch.

**Comment by lgarithm** [comment]
Could you try a clean clone?

**Comment by korejan** [comment]
> 
> 
> Could you try a clean clone?

@lgarithm working now, I merged your changes from lg-trace and all working with std tracer v0.2.1.
