### ISSUE TITLE
ERROR: ModelImporter.cpp:296 In function importModel: [5] Assertion failed: tensors.count(input_name)

### ISSUE THREAD

**Issue by 121649982** [tensorlayer/hyperpose#274]
when I use  MOdele "openpose_coco.onnx"  to inference,but I get this error.How to solve it ?Thank you

**Comment by ganler** [comment]
Hi @121649982 
Could you tell me about the platform configuration on your computer(TensorRT version, and which command you are using)?

**Comment by ganler** [comment]
@121649982 Just like what we claimed in the README, you can upgrade your TensorRT to version 7 or just install the onnx-tensorrt again.

The onnx-tenssort is not very steady and is still under development. So please use the newer version. 

Also see: https://github.com/onnx/onnx-tensorrt/issues/302#issuecomment-567958382
