### ISSUE TITLE
Converting model to .trt for use on Jetson AGX/DeepStream

### ISSUE THREAD

**Issue by ConnorM17** [tensorlayer/hyperpose#290]
I was wondering how I can use the OpenPose models here on my AGX with DeepStream. I've installed the OpenPose_coco.onnx model so far but I'm not really sure how to go about doing this.

**Comment by ganler** [comment]
Hi @ConnorM17 , if you have hyperpose along with the examples successfully compiled, you can try `./example.operator_api_imshow_paf --camera --model_file ../data/models/openpose_coco.onnx --input_width 656 --input_height 368` to play our project using your web camera. Also see https://hyperpose.readthedocs.io/en/latest/markdown/quick_start/prediction.html.

If you want to customize the usage, you can refer to our C++ API. https://hyperpose.readthedocs.io/en/latest/markdown/tutorial/prediction.html

**Comment by shuxuzhipeng** [comment]
> I was wondering how I can use the OpenPose models here on my AGX with DeepStream. I've installed the OpenPose_coco.onnx model so far but I'm not really sure how to go about doing this.

hello, have u succeded using it with deepstream, i use the same trt but the result of inference is different. do u have the correct result

**Comment by ishangupta3** [comment]
Hello @shuxuzhipeng  @ConnorM17 @ganler were you successful in building the deepstream file ?

**Comment by ConnorM17** [comment]
I have not looked into using Deepstream any further. However, with the current release of Hyperpose you can follow the tutorial to create a TensorRT .trt model file of the OpenPose models.

**Comment by ishangupta3** [comment]
Got it thanks, can you link me to the right area where I can find the tutorial for the tensor rt model of hyperpose?

**Comment by shuxuzhipeng** [comment]
> > I was wondering how I can use the OpenPose models here on my AGX with DeepStream. I've installed the OpenPose_coco.onnx model so far but I'm not really sure how to go about doing this.
> 
> hello, have u succeded using it with deepstream, i use the same trt but the result of inference is different. do u have the correct result

yes, when u deal with the output heatmap, in resize function u need to resize the heatmap 19*46*46 to the size of input layer. for example, usually the input is 3*356*356 i guess, u should resize the 19*46*46 heatmap to 19*356*356. then filter the keypoint and pass them into the data structure in deepstream.

**Comment by ishangupta3** [comment]
Right now, I am struggling with integrating TRT Pose, I am getting the PAF and cmap values from deepstream. But, the values are very off. Do you recommend for me to continue with attempting trt pose or using hyper pose?

Any information is greatly appreciated.

**Comment by ConnorM17** [comment]
> > > I was wondering how I can use the OpenPose models here on my AGX with DeepStream. I've installed the OpenPose_coco.onnx model so far but I'm not really sure how to go about doing this.
> > 
> > 
> > hello, have u succeded using it with deepstream, i use the same trt but the result of inference is different. do u have the correct result
> 
> yes, when u deal with the output heatmap, in resize function u need to resize the heatmap 19x46x46 to the size of input layer. for example, usually the input is 3x356x356 i guess, u should resize the 19x46x46 heatmap to 19x356x356. then filter the keypoint and pass them into the data structure in deepstream.

Have you been successful then with using deepstream with Hyperpose? Could you provide your code if possible?

**Comment by shuxuzhipeng** [comment]
> Right now, I am struggling with integrating TRT Pose, I am getting the PAF and cmap values from deepstream. But, the values are very off. Do you recommend for me to continue with attempting trt pose or using hyper pose?
> 
> Any information is greatly appreciated.

sorry ihave no idea, i used the  ./exectrt to convert the onnx to trt. As for the values of inference of trt, it's normal that it's different from the original onnx. because it modifies the network, but the keypoint wouldnot change i guess.

**Comment by shuxuzhipeng** [comment]
> > > I was wondering how I can use the OpenPose models here on my AGX with DeepStream. I've installed the OpenPose_coco.onnx model so far but I'm not really sure how to go about doing this.
> > 
> > 
> > hello, have u succeded using it with deepstream, i use the same trt but the result of inference is different. do u have the correct result
> 
> yes, when u deal with the output heatmap, in resize function u need to resize the heatmap 19x46x46 to the size of input layer. for example, usually the input is 3x356x356 i guess, u should resize the 19x46x46 heatmap to 19x356x356. then filter the keypoint and pass them into the data structure in deepstream.

no i just use the onnx file. sorry i cant commit the code.

**Comment by ishangupta3** [comment]
I will check it out thank you @shuxuzhipeng.
