### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by salvador-blanco** [tensorlayer/hyperpose#291]
Is there an example on how to make a prediction on an image using python?
If possible with all the associated data?

Heatmaps
Prediction bodyparts (x,y)
Image with a skeleton ?

**Comment by ganler** [comment]
Hi @salvador-blanco , you can do prediction using both python(only for training usage, therefore may not be efficient) and c++(highly optimized, but we have not implemented a python wrapper yet).

@Gyx-One Could you add an example of debugging/visualizing algorithms along with prediction API?

**Comment by Gyx-One** [comment]
@salvador-blanco  
Thanks for pointing out this issue!
 currently we exposes **preprocess**, **postprocess** and **visualize** API seperately to help user assemble thier own pipeline. 
 using them, it is easy to infer on one image to debugging, I'll add an example python code soon.

**Comment by Gyx-One** [comment]
@salvador-blanco 
Hello! I have already add a python example about inferring using python customize APIs, It's on the **infer.py**.
Thanks for using our library

**Comment by electroendjneer** [comment]
Hello! I'm trying to run the  hao28-pose345000.npz and the hao28-pose600000.npz models in infer.py, but I stumbled upon the following error:

`KeyError: 'params is not a file in the archive'`

If I replace line 15 in infer.py 
`model.load_weights(weight_path)`
with
`model.load_weights(weight_path,` format='npz_dict',skip = False)`

I stumbled, instead, upon the following warnung:

`[TL] WARNING: Weights named 'conv4_3_W' not found in network. Skip it.`

Ho can i load a model in TF correctly?

**Comment by Gyx-One** [comment]
> Hello! I'm trying to run the hao28-pose345000.npz and the hao28-pose600000.npz models in infer.py, but I stumbled upon the following error:
> 
> `KeyError: 'params is not a file in the archive'`
> 
> If I replace line 15 in infer.py
> `model.load_weights(weight_path)`
> 
> with:
> 
> `model.load_weights(weight_path, format='npz_dict',skip = False)`
> 
> but I have many warning like this:
> 
> `[TL] WARNING: Weights named 'conv4_3_W' not found in network. Skip it.`
> 
> How can I load a model in TF correctly?

Hello!  The reason of the warning *[TL] WARNING: Weights named 'conv4_3_W' not found in network. Skip it.*  is that the two models hao28-pose345000.npz and the hao28-pose600000.npz are trained by the first version of hyperpose which is compatible with tf 1.0, but now we update hyperpose to version 2.0 now where the network architectures are different from the old version, so load the these two npz model will lead to the mismatch in layers.(just as the warning said).
Thus to load a model, you should use the same **model type** (set by function *set_model_type*) and **model backbone** (set bu function *set_model_backbone*)  as the training configuration that produces the *.npz* model file (in current hyperpose 2.0 API), then load  the *.npz* file as the **infer.py**.

**Comment by carlosh93** [comment]
Hello, @Gyx-One I am having the same problem. Will you provide the npz files for the new hyperpose 2.0 implementation? I only need the pre-trained weights. Thank you!
