### ISSUE TITLE
possibility to use it in deepstream

### ISSUE THREAD

**Issue by shuxuzhipeng** [tensorlayer/hyperpose#295]
can i deploy it in deepstream, just use the onnx file and the corresponding trt file, deepstream also use tensorrt to realise the inference.

**Comment by shuxuzhipeng** [comment]
> can i deploy it in deepstream, just use the onnx file and the corresponding trt file, deepstream also use tensorrt to realise the inference.

`INFO: [FullDims Engine Info]: layers num: 3
0   INPUT  kFLOAT import/input_image:0 3x368x656       min: 1x3x368x656     opt: 20x3x368x656    Max: 20x3x368x656    
1   OUTPUT kFLOAT output_paf:0    38x46x82        min: 0               opt: 0               Max: 0               
2   OUTPUT kFLOAT output_conf:0   19x46x82        min: 0               opt: 0               Max: 0               

ERROR: [TRT]: INVALID_ARGUMENT: Cannot find binding of given name: output_conf
0:00:15.193601795   842      0x83ce160 WARN                 nvinfer gstnvinfer.cpp:599:gst_nvinfer_logger:<primary-inference> NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::checkBackendParams() <nvdsinfer_context_impl.cpp:1545> [UID = 1]: Could not find output layer 'output_conf' in engine
`
but the output layer name is not output_conf, why?

**Comment by shuxuzhipeng** [comment]
> > can i deploy it in deepstream, just use the onnx file and the corresponding trt file, deepstream also use tensorrt to realise the inference.
> 
> `INFO: [FullDims Engine Info]: layers num: 3
> 0 INPUT kFLOAT import/input_image:0 3x368x656 min: 1x3x368x656 opt: 20x3x368x656 Max: 20x3x368x656
> 1 OUTPUT kFLOAT output_paf:0 38x46x82 min: 0 opt: 0 Max: 0
> 2 OUTPUT kFLOAT output_conf:0 19x46x82 min: 0 opt: 0 Max: 0
> 
> ERROR: [TRT]: INVALID_ARGUMENT: Cannot find binding of given name: output_conf
> 0:00:15.193601795 842 0x83ce160 WARN nvinfer gstnvinfer.cpp:599:gst_nvinfer_logger: NvDsInferContext[UID 1]: Warning from NvDsInferContextImpl::checkBackendParams() <nvdsinfer_context_impl.cpp:1545> [UID = 1]: Could not find output layer 'output_conf' in engine
> `
> but the output layer name is not output_conf, why?

`./example.gen_serialized_engine --model_file ../data/models/openpose_coco.onnx --input_width 368 --input_height 368 --max_batch_size 20
` i use this to generate the engine file

**Comment by Y07yoyo** [comment]
Hi @shuxuzhipeng,

Were you able to get this working?

**Comment by ishangupta3** [comment]
Hello @Y07yoyo @shuxuzhipeng were you successful in getting this working?
