### ISSUE TITLE
UffParser error

### ISSUE THREAD

**Issue by justvasq** [tensorlayer/hyperpose#299]
I built with TensorRT support and tried to run ./example.operator_api_batched_images_paf

I got the following error:

ERROR: UffParser: Unsupported number of graph 0
ERROR: Failed to parse Uff in data type: float32

I tried the fix from #236 but no success

**Comment by ganler** [comment]
@justvasq Hi:

1. Have you already downloaded the models? This is shown in our [doc](https://hyperpose.readthedocs.io/en/latest/markdown/quick_start/prediction.html#install-test-models).
```bash
sh scripts/download-openpose-thin-model.sh      # ~20  MB
```
2. Did you execute the binary in the build folder? (I mean your superior directory should be the main folder of our repo, or you need to re-assign the flags(use `./example.operator_api_batched_images_paf --help` for guidance))
3. If you have already installed the model, the problem maybe the version of your TensorRT(It should be tensorrt 7).

Feel free to tell us your progress and thanks for using our library.
