### ISSUE TITLE
hand keypoint detection?

### ISSUE THREAD

**Issue by jinfagang** [tensorlayer/hyperpose#303]
Will this add an example on hand keypoint detection?

**Comment by ganler** [comment]
@jinfagang Hi, we currently focus on body arch detection. We are glad to support other keypoint detections but currently, we are still working on enhance the body detection part of it.

Also see: https://github.com/tensorlayer/hyperpose/issues/285#issuecomment-674566786

**Comment by ganler** [comment]
Closed due to inactivity.
