### ISSUE TITLE
Integrating into larger project cmake

### ISSUE THREAD

**Issue by stubbb** [tensorlayer/hyperpose#311]
[Help Wanted] [Good for newcomers]

Hello,

I am trying to integrate HyperPose with vendor specific camera SDK. I have my entire project using camera vendor SDK and OpenCV building and working correctly and my plan was to add the HyperPose to it.

I added the following to my cmake:

```
  ###HyperPose Includes
include_directories(/home/nvidia/HyperPose/hyperpose/include)
include_directories(/home/nvidia/HyperPose/hyperpose/include/operator/dnn)
include_directories(/home/nvidia/HyperPose/hyperpose/include/operator/parser)
include_directories(/home/nvidia/HyperPose/hyperpose/include/stream)
include_directories(/home/nvidia/HyperPose/hyperpose/include/utility)

include_directories(/home/nvidia/HyperPose/hyperpose/src)
include_directories(/home/nvidia/HyperPose/hyperpose/3rdparty/include)
#link_libraries(/home/nvidia/HyperPose/hyperpose/build/libstdtracer.a /home/nvidia/HyperPose/hyperpose/build/libhyperpose.a /home/nvidia/HyperPose/hyperpose/build/libhelpers.a)

INCLUDE(/home/nvidia/HyperPose/hyperpose/cmake/3rdparty.cmake)
```

I get through compilation but then at linker stage the following shows up:

```
main.cpp:(.text+0xd84): undefined reference to `hyperpose::dnn::tensorrt::tensorrt(hyperpose::dnn::uff const&, cv::Size_<int>, int, hyperpose::data_type, double, bool)'
main.cpp:(.text+0xdb0): undefined reference to `hyperpose::parser::paf::paf(cv::Size_<int>, float, float)'
main.cpp:(.text+0x11d8): undefined reference to `hyperpose::dnn::tensorrt::inference(std::vector<cv::Mat, std::allocator<cv::Mat> >)'
main.cpp:(.text+0x13e4): undefined reference to `hyperpose::parser::paf::process(hyperpose::feature_map_t const&, hyperpose::feature_map_t const&)'
main.cpp:(.text+0x1648): undefined reference to `hyperpose::draw_human(cv::Mat&, hyperpose::human_t_<18ul> const&)'
main.cpp:(.text+0x19a4): undefined reference to `hyperpose::parser::paf::~paf()'
main.cpp:(.text+0x19ac): undefined reference to `hyperpose::dnn::tensorrt::~tensorrt()'
main.cpp:(.text+0x1fe4): undefined reference to `hyperpose::dnn::tensorrt::~tensorrt()'
main.cpp:(.text+0x2020): undefined reference to `hyperpose::parser::paf::~paf()'
collect2: error: ld returned 1 exit status

```

Can you point me to what I am missing? Or is there a better way to integrate these two projects?

Regards,
Marcus G

**Comment by FlyingTiger2020** [comment]
Add the following in cmake/hyperpose.cmake and then use the generated .so file in building your project.

ADD_LIBRARY(
        ${POSE_LIB_NAME}so SHARED
        src/logging.cpp
        src/tensorrt.cpp
        src/paf.cpp
        src/data.cpp
        src/stream.cpp
        src/thread_pool.cpp
        src/pose_proposal.cpp
        src/human.cpp)

TARGET_LINK_LIBRARIES(
        ${POSE_LIB_NAME}so
        cudnn
        cudart
        nvinfer
        nvparsers
        nvonnxparser
        ${OpenCV_LIBS})

TARGET_INCLUDE_DIRECTORIES(${POSE_LIB_NAME}so
        PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>
        ${CUDA_RT}/include
        ${CUDA_RT}/include/crt)

SET_TARGET_PROPERTIES(${POSE_LIB_NAME}so PROPERTIES
        VERSION ${PROJECT_VERSION}
        SOVERSION ${PROJECT_VERSION})

**Comment by ganler** [comment]
Hi, what about just migrate your project into hyperpose, and add your camera SDK into the "helpers" in https://github.com/tensorlayer/hyperpose/blob/cd145ffe616ea60f1d258ee775c83c7d89fd7977/cmake/helpers.cmake#L19

Sorry for the inconvenience, in our next release I plan to make our C++ project more portable that users may add it to custom projects via CMake `ExternalProject`.

**Comment by stubbb** [comment]
> just migrate your project into hyperpose

That's what every project recommends  - base your project around our cmake/make/ninja/... :)

Thank you for not taking that path!

**Comment by ganler** [comment]
Closed. Thank you guys.

**Comment by orestis-z** [comment]
@ganler why is this closed? Is this project portable in the meantime?
