### ISSUE TITLE
Challenging dataset metrics vs OpenPose BODY25

### ISSUE THREAD

**Issue by stubbb** [tensorlayer/hyperpose#319]
Hello,

I run the metrics on my difficult test sample. It is a set of images that has motion blur, image ripping, overexposure, partially covered bodies, etc. 

Running OpenPose BODY25 on TX2:
-1x512: 93% ; 1.4 FPS
-1x368: 81% ; 2.1 FPS
-1x256: 72% ; 2.8 FPS
Running HyperPose on AGX Xavier:
onnx openpose thin V2 368x432: 46% ; 24 FPS 
onnx lopps resnet50 V2 368x432: 64% ; 19 FPS 
onnx pnn resnet50 V2 384x384: 22% ; 85 FPS 
onnx openpose coco V2 656x368: 90% ; 2.6 FPS 

AGX Xaveir should be roughly 2x faster, so estimated running 2.8 FPS -1x512 OP BODY_25. However, HP-OP_COCO model operates at 2.6 FPS with slightly poorer accuracy. Am I missing something? I envisioned TensorRT upgrade will provide some boost in terms of performance but this is applicable only at high accuracy loss. 

What would be the best model to hit high accuracy and improved FPS? Im trying to stay at comparable accuracy to OpenPose x368. Alternatively, would you recommend slicing an image to smaller chunks and using higher FPS models? Or, can I run high FPS model at much greater net resolution?

Thanks!

**Comment by ganler** [comment]
1. I will say that I prefer lopps given current models. However, we also have newer and better-trained models that I haven't upload to google drive as I am currently not around my workstation... I'll upload them in the weekend. Sorry for that...
2. For maximum accuracy you can try the Python version where we don't have limits about the input shape. And there's little difference between the C++ version and Python version and we'll get synchronized in the future(e.g., the training codes leverage some kinds of data augmentation). 
3. We didn't try to slice model into pieces for inference. You can have a try and see if it works. 

Thanks for using our library!

**Comment by stubbb** [comment]
@ganler Have you had a chance to upload some new models?

**Comment by ganler** [comment]
@stubbb Hi, the model uploading will be delayed a little bit as we met some trouble in converting the PPN model, but the openpose models are fine. I can send you some openpose models in which you can have variable input shapes. 

Just tell me how I can contact you via my email.

**Comment by stubbb** [comment]
@ganler Hi, thanks for the update, I included email in my profile: stubbb [at] gmail [dot] com

**Comment by ganler** [comment]
Closed.
