### ISSUE TITLE
infer.py

### ISSUE THREAD

**Issue by salvador-blanco** [tensorlayer/hyperpose#325]
I get different result by running the same project using `./example.operator_api_batched_images_paf` vs `infer.py`

`./example.operator_api_batched_images_paf`  followed by `infer.py` :
 
![sample2_o](https://user-images.githubusercontent.com/30084029/95417056-113a8600-096f-11eb-832a-2fc61582f423.png)
![sample2_paf](https://user-images.githubusercontent.com/30084029/95417064-14357680-096f-11eb-992f-ea2170363e07.png)

![image1_o](https://user-images.githubusercontent.com/30084029/95417020-fd8f1f80-096e-11eb-929e-f1c7bf620bb3.png)
![image1_paf](https://user-images.githubusercontent.com/30084029/95417031-008a1000-096f-11eb-8684-09a7572cf003.png)

![sample_o](https://user-images.githubusercontent.com/30084029/95417099-26afb000-096f-11eb-8c92-70abcd4969bd.png)
![sample_paf](https://user-images.githubusercontent.com/30084029/95417104-29120a00-096f-11eb-96ff-6e29d8822834.png)

Would it also be possible to make the drawn skeletons by `infer.py` similar to the ones drawn by `./example.operator_api_batched_images_paf`. Different parts different colors ?

**Comment by ganler** [comment]
@salvador-blanco Hi this is possible.
There are some differences between the training codes and inference codes that I think may not be strictly aligned.

They are different in :

1. Input resolution: In our C++ codes, only fixed input resolution is allowed, but it is variable in the python code base.
2. Inference framework: C++: tensorrt, python: TensorLayer/TensorFlow
3. Post processing thresholds: There're some thresholds about the key point and limbs, that the 2 codebase may not comport with each other.
