### ISSUE TITLE
How to install libopencv-dev on Ubuntu 16.04 

### ISSUE THREAD

**Issue by pingzhenyu** [tensorlayer/hyperpose#334]
I'm trying to install OpenCV (video analytics) and am following the Ubuntu OpenCV installation documentation.

(hyperpose) root@7920-Tower:~/hyperpose/build# apt-get install libopencv-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopencv-dev : Depends: libopencv-core-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed
                 Depends: libopencv-ml-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed
                 Depends: libopencv-imgproc-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed
                 Depends: libopencv-video-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

**Comment by stubbb** [comment]
3rd party dependencies have appropriate channels for communication, this repo is strictly about Hyperpose.
