### ISSUE TITLE
annotation tool

### ISSUE THREAD

**Issue by pingzhenyu** [tensorlayer/hyperpose#337]
First of all I want to thank you for this great work, I want to train the model on my own data but I do not know which annotation tool I will use **can you advise me**?
Thank you.

**Comment by lengyuner** [comment]
DeepLabCut

**Comment by pingzhenyu** [comment]
DeepLabCut？a software package for animal pose estimation.
https://github.com/DeepLabCut/

**Comment by lengyuner** [comment]
yep, it is easy to use
good luck

**Comment by lengyuner** [comment]
And maybe tomorrow I will push a easy tool to annotate on my git

**Comment by pingzhenyu** [comment]
Thank you very much
