### ISSUE TITLE
build  myself code about ERROR: Tensor image cannot be both input and output

### ISSUE THREAD

**Issue by zhanghongyong123456** [tensorlayer/hyperpose#379]
Build my own code(https://github.com/tensorlayer/hyperpose/blob/master/examples/tutorial/minimum_operator_api_video.example.cpp) and prompt me this error when I compile successfully(https://hyperpose.readthedocs.io/en/latest/markdown/install/prediction.html) and run   ./user.main

about error  :ERROR: Tensor image cannot be both input and output

**Comment by ganler** [comment]
@zhanghongyong123456  This is a TensorRT error. Please just ignore it. See https://hyperpose.readthedocs.io/en/latest/markdown/tutorial/faq.html#tensorrt-error
