### ISSUE TITLE
Pose Proposal Networks, ECCV 2018 in TensorFlow

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/hyperpose#53]
Combine YOLO and OpenPose -- 200 FPS

**Comment by lyupei** [comment]
will this be implemented?

**Comment by zsdonghao** [comment]
yeah, it is on the TODO list

**Comment by wm901115nwpu** [comment]
what's time will open the code?

**Comment by zsdonghao** [comment]
@wm901115nwpu as it is a open-source project, we can't tell when.

**Comment by luomai** [comment]
We are currently working on the integration of TensorRT to make the inference super fast and low-latency. Once we finish that, we will consider working on the next TODO on the list.

**Comment by luomai** [comment]
@wm901115nwpu @lyupei

**Comment by lyupei** [comment]
@luomai Great! 3ks for reply!

**Comment by shreyasrajesh** [comment]
Is there any code available open source for Pose Proposal Networks, or do you plan on writing it from scratch ?

**Comment by ariel415el** [comment]
I just found out about that : https://github.com/Idein/chainer-pose-proposal-net

Hope if enough users will try it it will work smoothly 


Ariel.

**Comment by wangziren1** [comment]
Hi, I have implemented the pytorch version of pose proposal networks but don't evaluate the performance. If anyone is interested in it, click   @[here](https://github.com/wangziren1/pytorch_pose_proposal_network).

**Comment by jovialio** [comment]
> Hi, I have implemented the pytorch version of pose proposal networks but don't evaluate the performance. If anyone is interested in it, click [here](https://github.com/wangziren1/pytorch_pose_proposal_network).

Nice...Saw the problems you mentioned in your README. Will take a closer look at it if there's opportunity. Nonetheless good work.
