### ISSUE TITLE
Implement Python binding for PAF process (#56)

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/hyperpose#57]
## Test data:
[network-output.npz.gz](https://github.com/tensorlayer/fast-openpose/files/2374263/network-output.npz.gz)

**Comment by lgarithm** [comment]
Currently you can use [uff-runner.py](https://github.com/tensorlayer/openpose-plus/blob/master/examples/uff-runner.py) (it is using https://github.com/ildoonet/tf-pose-estimation/trunk/tf_pose/pafprocess, you need to install it by running `./scripts/install-pafprocess.sh`), see [run-uff-py.sh](https://github.com/tensorlayer/openpose-plus/blob/master/scripts/run-uff-py.sh) for detailed usage.

Eventually we will replace the post processing part with our own implementation, which re-implements the algorithm from tf-pose-estimation, but with several improvements, e.g. thread safety.

**Comment by mengzhangjian** [comment]
@lgarithm , uff-runner.py can not be used on tx2. While there is no tensorRT python inferface API for tx2 .
